import {useEffect,useState} from 'react'
import {Card} from '../components/Card'
import {recordsRepository} from '../repositories'
import {summarizeMonth,summarizeYear,type Summary} from '../services/analysisService'
import {loadAnalysisSettings,loadCalendar} from '../services/appDataService'
import {localISODate} from '../services/calendarService'
import {compSettlementForMonth,currentLeaveSummary} from '../services/ledgerCoordinator'
import {LEDGER_CHANGED,ledgerEvents} from '../services/ledgerService'
import {nextMonth,previousMonth} from '../utils/date'
import {formatMinutes} from '../utils/time'
const empty:Summary={workMinutes:0,attendanceDays:0,averageMinutes:0,overtimeMinutes:0,shortfallMinutes:0,holidayWorkMinutes:0,scheduledWorkdays:0,missingWorkdays:0}
export function AnalysisPage(){
 const now=new Date(),[value,setValue]=useState({year:now.getFullYear(),month:now.getMonth()+1}),[summary,setSummary]=useState(empty),[leave,setLeave]=useState<Awaited<ReturnType<typeof currentLeaveSummary>>|null>(null),[settlement,setSettlement]=useState<Awaited<ReturnType<typeof compSettlementForMonth>>>(undefined),[yearSummary,setYearSummary]=useState({workMinutes:0,attendanceDays:0})
 useEffect(()=>{const refresh=()=>void(async()=>{const [records,yearRecords,calendar,settings,balances,monthSettlement]=await Promise.all([recordsRepository.recordsForMonth(value.year,value.month),recordsRepository.recordsForYear(value.year),loadCalendar([value.year]),loadAnalysisSettings(localISODate()),currentLeaveSummary(),compSettlementForMonth(value.year,value.month)]);setLeave(balances);setSettlement(monthSettlement);setYearSummary(summarizeYear(yearRecords,value.year));setSummary(summarizeMonth(records,calendar,{year:value.year,month:value.month,...settings,calculationStartDate:settings.calculationStartDate as `${number}-${number}-${number}`}))})();refresh();ledgerEvents.addEventListener(LEDGER_CHANGED,refresh);return()=>ledgerEvents.removeEventListener(LEDGER_CHANGED,refresh)},[value])
 const metrics:[string,string][]=[['目前可用補休',leave?formatMinutes(leave.total):'計算中…'],...(leave?.dailyCapEnabled?[['年度待結算時數',formatMinutes(leave.annualExcessPendingMinutes)],['已完成年度超額結算',`NT$${Math.floor(leave.annualExcessSettledCents/100).toLocaleString()}`]]:[]) as [string,string][],['目前特休餘額',leave?formatMinutes(leave.annualBalanceMinutes):'計算中…'],...(leave?.mode==='MONTHLY'?[['本月新增／剩餘補休',formatMinutes(leave.monthly)],['年度累積補休',formatMinutes(leave.annual)],...(settlement?[['本月轉入年補休',formatMinutes(settlement.transferToAnnualMinutes)],['本月超額折現時數',formatMinutes(settlement.cashMinutes)],['本月折現金額',`NT$${Math.floor(settlement.cashAmountCents/100).toLocaleString()}`]]:[])]:[]) as [string,string][],['本月總工時',formatMinutes(summary.workMinutes)],['實際出勤天數',`${summary.attendanceDays} 天`],['平均每日工時',formatMinutes(summary.averageMinutes)],['超時',formatMinutes(summary.overtimeMinutes)],['不足',formatMinutes(summary.shortfallMinutes)],['假日工作',formatMinutes(summary.holidayWorkMinutes)],['預定工作日',`${summary.scheduledWorkdays} 天`],['缺少工時紀錄',`${summary.missingWorkdays} 天`],['年度總工時',formatMinutes(yearSummary.workMinutes)],['年度出勤',`${yearSummary.attendanceDays} 天`]]
 return <><div className="eyebrow">月份統計</div><div className="month-switch"><button aria-label="上個月" onClick={()=>setValue(previousMonth(value))}>‹</button><h2>{value.year} 年 {value.month} 月</h2><button aria-label="下個月" onClick={()=>setValue(nextMonth(value))}>›</button></div><div className="metric-grid">{metrics.map(([name,result])=><Card key={name}><span>{name}</span><strong>{result}</strong></Card>)}</div><Card title="計算說明"><p className="explanation-intro">不足時數包含兩部分：</p><ol className="explanation-list"><li>已有紀錄，但工時未達標準的日子</li><li>從工時計算起始日到今天之前，應上班但沒有登記工時的日子</li></ol><p className="explanation-note">假別餘額會依目前所有紀錄自動計算。</p></Card></>
}
