import { useEffect,useState } from 'react'
import { Card } from '../components/Card'
import { recordsRepository } from '../repositories'
import { summarizeMonth,type Summary } from '../services/analysisService'
import { loadAnalysisSettings,loadCalendar } from '../services/appDataService'
import { localISODate } from '../services/calendarService'
import { currentLeaveSummary,rebuildLedger } from '../services/ledgerCoordinator'
import { LEDGER_CHANGED,ledgerEvents } from '../services/ledgerService'
import { WORK_RECORDS_CHANGED,workRecordEvents } from '../services/workRecordMutations'
import { calculateWorkMinutes } from '../services/workTimeService'
import { formatMinutes } from '../utils/time'
import {ExcelExportService,type ExcelArtifact} from '../services/excelExportService'
import type {ExcelExportScope} from '../services/excelReportBuilder'
import {PreparedFileActions} from '../components/PreparedFileActions'
const blank:Summary={workMinutes:0,attendanceDays:0,averageMinutes:0,overtimeMinutes:0,shortfallMinutes:0,holidayWorkMinutes:0,scheduledWorkdays:0,missingWorkdays:0}
export async function loadHomeSummary(today=localISODate()){const year=Number(today.slice(0,4)),month=Number(today.slice(5,7));const [records,todayRecord,calendar,settings]=await Promise.all([recordsRepository.recordsForMonth(year,month),recordsRepository.getByDate(today),loadCalendar([year]),loadAnalysisSettings(today)]);await rebuildLedger(today as `${number}-${number}-${number}`,false);return {todayMinutes:todayRecord?calculateWorkMinutes(todayRecord):0,month:summarizeMonth(records,calendar,{year,month,...settings,calculationStartDate:settings.calculationStartDate as `${number}-${number}-${number}`,today}),leave:await currentLeaveSummary(today as `${number}-${number}-${number}`)}}
export function HomePage(){const [data,setData]=useState(blank),[todayMinutes,setTodayMinutes]=useState(0),[leave,setLeave]=useState<Awaited<ReturnType<typeof currentLeaveSummary>>|null>(null),[error,setError]=useState(''),[scope,setScope]=useState<ExcelExportScope>('all'),[exportBusy,setExportBusy]=useState(false),[exportMessage,setExportMessage]=useState(''),[prepared,setPrepared]=useState<ExcelArtifact>();useEffect(()=>{const refresh=()=>{void loadHomeSummary().then(result=>{setTodayMinutes(result.todayMinutes);setData(result.month);setLeave(result.leave);setError('')}).catch(()=>setError('摘要或假別餘額載入失敗，請稍後再試。'))};refresh();workRecordEvents.addEventListener(WORK_RECORDS_CHANGED,refresh);ledgerEvents.addEventListener(LEDGER_CHANGED,refresh);return()=>{workRecordEvents.removeEventListener(WORK_RECORDS_CHANGED,refresh);ledgerEvents.removeEventListener(LEDGER_CHANGED,refresh)}},[]);async function exportExcel(){if(exportBusy)return;setExportBusy(true);setExportMessage('');try{const artifact=await new ExcelExportService().create(scope);setPrepared(artifact);setExportMessage('Excel 已準備完成。')}catch(reason){setPrepared(undefined);setExportMessage(`Excel 建立失敗｜原因：${reason instanceof Error?reason.message:'請稍後再試。'}`)}finally{setExportBusy(false)}}return <><div className="eyebrow">本月摘要</div><h2 className="page-title">掌握每一分鐘</h2>{error&&<p className="notice" role="alert">{error}</p>}<div className="metric-grid"><Card><span>今日工時</span><strong>{formatMinutes(todayMinutes)}</strong></Card><Card><span>本月工時</span><strong>{formatMinutes(data.workMinutes)}</strong></Card><Card><span>{leave?.mode==='MONTHLY'?'目前可用補休':'目前補休'}</span><strong>{leave?formatMinutes(leave.total):'計算中…'}</strong>{leave?.mode==='MONTHLY'&&<small>本月：{formatMinutes(leave.monthly)}<br/>年度：{formatMinutes(leave.annual)}</small>}</Card><Card><span>特休餘額</span><strong>{leave?formatMinutes(leave.annualBalanceMinutes):'計算中…'}</strong></Card><Card><span>本月出勤</span><strong>{data.attendanceDays} 天</strong></Card><Card><span>本月超時</span><strong>{formatMinutes(data.overtimeMinutes)}</strong></Card><Card><span>本月不足</span><strong>{formatMinutes(data.shortfallMinutes)}</strong></Card></div><Card title="Excel 報表"><div className="export-controls"><label htmlFor="excel-export-scope">匯出範圍<select id="excel-export-scope" value={scope} onChange={event=>setScope(event.target.value as ExcelExportScope)} disabled={exportBusy}><option value="all">全部紀錄</option><option value="leave_year">今年度</option></select></label><button type="button" disabled={exportBusy} aria-busy={exportBusy} onClick={()=>void exportExcel()}>{exportBusy?'建立中…':'建立 Excel'}</button></div>{exportMessage&&<p className="notice" role={exportMessage.startsWith('Excel 建立失敗')?'alert':'status'}>{exportMessage}</p>}{prepared&&<PreparedFileActions key={prepared.filename} file={{...prepared,description:'Excel 活頁簿',extension:'.xlsx'}} saveLabel="儲存 Excel" downloadLabel="下載 Excel"/>}</Card></>}
