import { useState, type FormEvent } from 'react'
import { Card } from '../components/Card'
import { announceWorkRecordsChanged, useRecentWorkRecords } from '../hooks/useWorkRecords'
import type { ISODate, WorkRecord } from '../models/domain'
import { workRecordRepository } from '../repositories'
import { calculateWorkTime, type WorkTimeResult } from '../services/workTimeService'
import { localISODate } from '../utils/date'
import { formatMinutes } from '../utils/time'

const blankRecord=():WorkRecord=>({workDate:localISODate(),clockIn:'08:00',clockOut:'17:00',breakStart:'12:00',breakEnd:'13:00',deductBreak:true,standardMinutes:480,note:'',workdayType:'正常工作日',overnight:false})
export function RecordsPage(){
 const [form,setForm]=useState<WorkRecord>(blankRecord),[result,setResult]=useState<WorkTimeResult>(),[error,setError]=useState('');const {records,loading}=useRecentWorkRecords(7)
 const change=<K extends keyof WorkRecord>(key:K,value:WorkRecord[K])=>setForm(current=>({...current,[key]:value}))
 const submit=async(event:FormEvent)=>{event.preventDefault();setError('');try{const calculated=calculateWorkTime(form),id=await workRecordRepository.save(form);setForm(current=>({...current,id}));setResult(calculated);announceWorkRecordsChanged()}catch(reason){setError(reason instanceof Error?reason.message:'無法儲存紀錄。')}}
 const edit=(record:WorkRecord)=>{setForm({...record});setResult(calculateWorkTime(record));setError('');window.scrollTo({top:0,behavior:'smooth'})}
 const remove=async(record:WorkRecord)=>{if(record.id===undefined||!window.confirm(`確定刪除 ${record.workDate} 的工時紀錄？`))return;await workRecordRepository.delete(record.id);if(form.id===record.id){setForm(blankRecord());setResult(undefined)}announceWorkRecordsChanged()}
 return <><div className="eyebrow">每日紀錄</div><h2 className="page-title">{form.id===undefined?'新增工時':'修改工時'}</h2><Card><form onSubmit={submit}><div className="form-grid"><label>日期<input required type="date" value={form.workDate} onChange={event=>change('workDate',event.target.value as ISODate)}/></label><label>標準工時（分鐘）<input required min="0" type="number" value={form.standardMinutes} onChange={event=>change('standardMinutes',Number(event.target.value))}/></label><label>上班時間<input required type="time" value={form.clockIn} onChange={event=>change('clockIn',event.target.value)}/></label><label>下班時間<input required type="time" value={form.clockOut} onChange={event=>change('clockOut',event.target.value)}/></label><label className="checkbox wide"><input type="checkbox" checked={form.overnight} onChange={event=>change('overnight',event.target.checked)}/>跨午夜下班</label><label className="wide">備註<input value={form.note} onChange={event=>change('note',event.target.value)} placeholder="選填"/></label></div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions">{form.id!==undefined&&<button type="button" className="secondary" onClick={()=>{setForm(blankRecord());setResult(undefined);setError('')}}>取消修改</button>}<button type="submit">儲存紀錄</button></div></form></Card><Card title="本日工時">{result?<><strong>{formatMinutes(result.actualWorkMinutes)}</strong><p className={result.shortfallMinutes?'negative':'positive'}>{result.overtimeMinutes?`超時 ${formatMinutes(result.overtimeMinutes)}`:result.shortfallMinutes?`不足 ${formatMinutes(result.shortfallMinutes)}`:'符合標準工時'}</p></>:<p className="empty">儲存後顯示計算結果</p>}</Card><Card title="最近紀錄">{loading?<p className="empty">載入中…</p>:records.length===0?<p className="empty">尚無工時紀錄</p>:<div className="record-list">{records.map(record=><article key={record.id}><div><strong>{record.workDate}</strong><span>{record.clockIn} - {record.clockOut}{record.overnight?'（跨日）':''}</span><span>工時 {formatMinutes(calculateWorkTime(record).actualWorkMinutes)}</span>{record.note&&<span>{record.note}</span>}</div><div className="row-actions"><button className="secondary" onClick={()=>edit(record)}>修改</button><button className="danger" onClick={()=>void remove(record)}>刪除</button></div></article>)}</div>}</Card></>
}
