import { useEffect, useState, type FormEvent } from 'react'
import { Card } from '../components/Card'
import type { CalendarDayType, CalendarOverride, ISODate, OfficialHoliday } from '../models/domain'
import { holidayRepository, settingsRepository, specialDateRepository } from '../repositories'
import { localISODate } from '../services/calendarService'

const now=localISODate()
export function SettingsPage(){
  const [hours,setHours]=useState(8),[minutes,setMinutes]=useState(0),[lunchStart,setLunchStart]=useState('12:00'),[lunchEnd,setLunchEnd]=useState('13:00'),[trackingStart,setTrackingStart]=useState<string>(now)
  const [date,setDate]=useState<string>(now),[dayType,setDayType]=useState<CalendarDayType>('NON_WORKDAY'),[note,setNote]=useState(''),[overrides,setOverrides]=useState<CalendarOverride[]>([]),[message,setMessage]=useState('')
  const [holidayJson,setHolidayJson]=useState(''),[holidayStatus,setHolidayStatus]=useState('尚未匯入官方假日資料')
  async function refresh(){setOverrides(await specialDateRepository.all())}
  useEffect(()=>{void (async()=>{const standard=Number(await settingsRepository.get('daily_standard_minutes','480'));setHours(Math.floor(standard/60));setMinutes(standard%60);setLunchStart((await settingsRepository.get('lunch_break_start','12:00'))!);setLunchEnd((await settingsRepository.get('lunch_break_end','13:00'))!);let start=await settingsRepository.get('work_tracking_start_date');if(!start){start=now;await settingsRepository.set({key:'work_tracking_start_date',value:start})}setTrackingStart(start);await refresh()})()},[])
  async function saveSettings(event:FormEvent){event.preventDefault();const total=hours*60+minutes;if(!Number.isInteger(total)||total<=0){setMessage('每日標準工時必須大於 0 分鐘。');return}if(lunchEnd<=lunchStart){setMessage('午休結束必須晚於午休開始。');return}await settingsRepository.set({key:'daily_standard_minutes',value:String(total)});await settingsRepository.setLunchBreak(lunchStart,lunchEnd);await settingsRepository.set({key:'work_tracking_start_date',value:trackingStart});setMessage('設定已儲存；既有紀錄保存原 standardMinutes。')}
  async function saveOverride(event:FormEvent){event.preventDefault();const stamp=new Date().toISOString(),existing=await specialDateRepository.get(date);await specialDateRepository.save({workDate:date as ISODate,dayType,note:note.trim(),createdAt:existing?.createdAt??stamp,updatedAt:stamp});setNote('');await refresh()}
  async function importHolidays(){try{const parsed=JSON.parse(holidayJson) as Array<{date:string;name:string}>,year=Number(parsed[0]?.date.slice(0,4));if(!year||parsed.some((x)=>!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||Number(x.date.slice(0,4))!==year))throw new Error('同一次匯入只能包含一個年份的 ISO 日期。');const stamp=new Date().toISOString(),values:OfficialHoliday[]=parsed.map((x)=>({holidayDate:x.date as ISODate,name:x.name,year,source:'MANUAL_IMPORT',syncedAt:stamp}));await holidayRepository.replaceYear(year,values);setHolidayStatus(`${year} 年已快取 ${values.length} 筆假日。`)}catch(error){setHolidayStatus(error instanceof Error?error.message:'匯入失敗。')}}
  return <><div className="eyebrow">個人化規則</div><h2 className="page-title">設定</h2><Card title="基本工時與午休"><form onSubmit={saveSettings}><div className="form-grid"><label>每日標準小時<input type="number" min="0" max="23" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label>每日標準分鐘<input type="number" min="0" max="59" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>午休開始<input type="time" value={lunchStart} onChange={e=>setLunchStart(e.target.value)}/></label><label>午休結束<input type="time" value={lunchEnd} onChange={e=>setLunchEnd(e.target.value)}/></label><label className="wide">工時計算起始日<input type="date" required value={trackingStart} onChange={e=>setTrackingStart(e.target.value)}/></label></div><button type="submit">儲存工時設定</button></form>{message&&<p className="notice">{message}</p>}</Card><Card title="特殊日期"><form onSubmit={saveOverride}><div className="form-grid"><label>日期<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>類型<select value={dayType} onChange={e=>setDayType(e.target.value as CalendarDayType)}><option value="WORKDAY">WORKDAY</option><option value="NON_WORKDAY">NON_WORKDAY</option></select></label><label className="wide">備註<input value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：公司補班"/></label></div><button type="submit">新增 / 儲存特殊日期</button></form><div className="item-list">{overrides.map(row=><div className="list-row" key={row.workDate}><div><strong>{row.workDate}</strong><span>{row.dayType} {row.note&&`· ${row.note}`}</span></div><button className="danger small" onClick={()=>void specialDateRepository.deleteByDate(row.workDate).then(refresh)}>刪除</button></div>)}{!overrides.length&&<p className="empty">尚無特殊日期</p>}</div></Card><Card title="官方假日離線快取"><p>貼上單一年度 JSON 陣列，例如 <code>[{`{"date":"2026-10-10","name":"國慶日"}`}]</code>。匯入會取代該年度快取。</p><textarea value={holidayJson} onChange={e=>setHolidayJson(e.target.value)} rows={4}/><button onClick={()=>void importHolidays()}>匯入 / 更新假日</button><p className="notice">{holidayStatus}</p><span className="badge">Network sync · PARTIAL</span></Card><Card title="尚未移植"><p>Ledger、補休、特休、假別轉換與備份還原留待後續階段。</p><span className="badge">NOT IMPLEMENTED</span></Card></>
}
