import { useEffect,useState,type FormEvent } from 'react'
import { Card } from '../components/Card'
import type { CalendarOverride,ISODate,SpecialDateCategory } from '../models/domain'
import { holidayRepository,settingsRepository,specialDateRepository } from '../repositories'
import { localISODate } from '../services/calendarService'
import { parseHolidayPackage,updatePackagedHolidayYear } from '../services/holidayService'
import { categoryToDayType,SPECIAL_DATE_LABELS } from '../services/specialDateService'

const now=localISODate(),currentYear=Number(now.slice(0,4)),holidayYears=[currentYear,currentYear+1]
export function SettingsPage(){
  const [hours,setHours]=useState(8),[minutes,setMinutes]=useState(0),[lunchStart,setLunchStart]=useState('12:00'),[lunchEnd,setLunchEnd]=useState('13:00'),[trackingStart,setTrackingStart]=useState<string>(now)
  const [date,setDate]=useState<string>(now),[category,setCategory]=useState<SpecialDateCategory>('SPECIAL_NON_WORKDAY'),[note,setNote]=useState(''),[overrides,setOverrides]=useState<CalendarOverride[]>([]),[message,setMessage]=useState('')
  const [holidayJson,setHolidayJson]=useState(''),[holidayStatus,setHolidayStatus]=useState<Record<number,string>>({}),[holidayMessage,setHolidayMessage]=useState('')
  async function refresh(){setOverrides(await specialDateRepository.all())}
  async function refreshHolidayStatus(){const entries=await Promise.all(holidayYears.map(async year=>{const values=await holidayRepository.forYear(year),updated=await settingsRepository.get(`holiday_updated_${year}`);return [year,values.length?`已載入 ${values.length} 筆${updated?` · 最後更新 ${new Date(updated).toLocaleString()}`:''}`:'尚未載入'] as const}));setHolidayStatus(Object.fromEntries(entries))}
  useEffect(()=>{void (async()=>{try{const standard=Number(await settingsRepository.get('daily_standard_minutes','480'));setHours(Math.floor(standard/60));setMinutes(standard%60);setLunchStart((await settingsRepository.get('lunch_break_start','12:00'))!);setLunchEnd((await settingsRepository.get('lunch_break_end','13:00'))!);let start=await settingsRepository.get('work_tracking_start_date');if(!start){start=now;await settingsRepository.set({key:'work_tracking_start_date',value:start})}setTrackingStart(start);await Promise.all([refresh(),refreshHolidayStatus()])}catch{setMessage('設定載入失敗，請稍後再試。')}})()},[])
  async function saveSettings(event:FormEvent){event.preventDefault();try{const total=hours*60+minutes;if(!Number.isInteger(total)||total<=0){setMessage('每日標準工時必須大於 0 分鐘。');return}if(lunchEnd<=lunchStart){setMessage('午休結束必須晚於午休開始。');return}await settingsRepository.set({key:'daily_standard_minutes',value:String(total)});await settingsRepository.setLunchBreak(lunchStart,lunchEnd);await settingsRepository.set({key:'work_tracking_start_date',value:trackingStart});setMessage('設定已儲存；既有紀錄保存原標準工時。')}catch{setMessage('設定儲存失敗，原設定仍保留。')}}
  async function saveOverride(event:FormEvent){event.preventDefault();try{const stamp=new Date().toISOString(),existing=await specialDateRepository.get(date);await specialDateRepository.save({workDate:date as ISODate,category,dayType:categoryToDayType(category),note:note.trim(),createdAt:existing?.createdAt??stamp,updatedAt:stamp});setNote('');setMessage('特殊日期已儲存。');await refresh()}catch{setMessage('特殊日期儲存失敗。')}}
  async function removeOverride(row:CalendarOverride){if(!window.confirm(`確定刪除 ${row.workDate} 的特殊日期？`))return;try{await specialDateRepository.deleteByDate(row.workDate);await refresh()}catch{setMessage('特殊日期刪除失敗。')}}
  async function updateHolidays(){setHolidayMessage('更新中…');const results=await Promise.all(holidayYears.map(async year=>{try{const values=await updatePackagedHolidayYear(year,holidayRepository,settingsRepository);return `${year}：已載入 ${values.length} 筆`}catch{return `${year}：更新失敗，使用現有資料`}}));setHolidayMessage(results.join('；'));await refreshHolidayStatus()}
  async function importHolidays(){try{const parsed=parseHolidayPackage(JSON.parse(holidayJson),new Date().toISOString());await holidayRepository.replaceYear(parsed.year,parsed.values);await settingsRepository.set({key:`holiday_updated_${parsed.year}`,value:new Date().toISOString()});setHolidayMessage(`${parsed.year}：已匯入 ${parsed.values.length} 筆`);await refreshHolidayStatus()}catch{setHolidayMessage('匯入失敗，使用現有資料。請確認年度、日期、名稱與重複日期。')}}
  return <><div className="eyebrow">個人化規則</div><h2 className="page-title">設定</h2><Card title="基本工時與午休"><form onSubmit={saveSettings}><div className="form-grid"><label>每日標準小時<input type="number" min="0" max="23" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label>每日標準分鐘<input type="number" min="0" max="59" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>午休開始<input type="time" value={lunchStart} onChange={e=>setLunchStart(e.target.value)}/></label><label>午休結束<input type="time" value={lunchEnd} onChange={e=>setLunchEnd(e.target.value)}/></label><label className="wide">工時計算起始日<input type="date" required value={trackingStart} onChange={e=>setTrackingStart(e.target.value)}/></label></div><button type="submit">儲存工時設定</button></form>{message&&<p className="notice" role="status">{message}</p>}</Card><Card title="特殊日期"><form onSubmit={saveOverride}><div className="form-grid"><label>日期<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>類型<select value={category} onChange={e=>setCategory(e.target.value as SpecialDateCategory)}>{Object.entries(SPECIAL_DATE_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="wide">備註<input value={note} onChange={e=>setNote(e.target.value)} placeholder="選填，例如：公司活動"/></label></div><button type="submit">新增 / 儲存特殊日期</button></form><div className="item-list">{overrides.map(row=><div className="list-row" key={row.workDate}><div><strong>{row.workDate}</strong><span>{SPECIAL_DATE_LABELS[row.category??(row.dayType==='WORKDAY'?'COMPANY_MAKEUP_WORKDAY':'SPECIAL_NON_WORKDAY')]} {row.note&&`· ${row.note}`}</span></div><button className="danger small" onClick={()=>void removeOverride(row)}>刪除</button></div>)}{!overrides.length&&<p className="empty">尚無特殊日期</p>}</div></Card><Card title="台灣官方假日"><p>內建政府辦公日曆資料會驗證後快取至裝置；更新失敗不會刪除既有資料。</p><div className="holiday-status">{holidayYears.map(year=><span key={year}><strong>{year}</strong>{holidayStatus[year]??'讀取中…'}</span>)}</div><button onClick={()=>void updateHolidays()}>更新官方假日</button>{holidayMessage&&<p className="notice" role="status">{holidayMessage}</p>}<details><summary>進階：匯入假日 JSON</summary><label>假日 JSON<textarea value={holidayJson} onChange={e=>setHolidayJson(e.target.value)} rows={4} placeholder='{"year":2026,"source":"...","holidays":[...]}'/></label><button onClick={()=>void importHolidays()}>驗證並匯入</button></details></Card><Card title="後續階段"><p>Ledger、補休、特休、假別轉換與備份還原留待後續階段。</p><span className="badge">INTENTIONALLY DEFERRED</span></Card></>
}
