"""Observable Briefcase mobile build, APK collection, reports, and diagnostics."""

from __future__ import annotations
import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import shutil
import subprocess
import sys
import tomllib
import zipfile
import xml.etree.ElementTree as ET
from typing import NamedTuple
from datetime import datetime, timezone
from pathlib import Path
from src.worktime_tracker.config import APP_VERSION, BUILD_SIZE_WARNING_MB

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build"
RELEASE = ROOT / "release"
ANDROID_RELEASE = RELEASE / "android"
LOG_PATH = RELEASE / "build_android.log"
APP_FILENAME = "工時管家"
SIGNING_ENV_VARS = (
    "ANDROID_KEYSTORE",
    "ANDROID_KEY_ALIAS",
    "ANDROID_KEYSTORE_PASSWORD",
    "ANDROID_KEY_PASSWORD",
)
MATERIAL_DEPENDENCY = "com.google.android.material:material:1.12.0"
ANDROID_NAMESPACE = "http://schemas.android.com/apk/res/android"
BACKUP_POLICY = ROOT / "android" / "backup_policy.json"
BACKUP_RULES = ROOT / "android" / "backup_rules.xml"
BACKUP_RULES_LEGACY = ROOT / "android" / "backup_rules_legacy.xml"


class ApkInspection(NamedTuple):
    complete: bool
    signed: bool
    abis: list[str]
    signature_verification: str
    details: str = ""


class Tee:
    """Mirror Python and child-process output to the console and build log."""

    def __init__(self, *streams):
        self.streams = streams

    def write(self, value: str) -> int:
        for stream in self.streams:
            stream.write(value)
            stream.flush()
        return len(value)

    def flush(self) -> None:
        for stream in self.streams:
            stream.flush()


def enable_logging():
    RELEASE.mkdir(parents=True, exist_ok=True)
    log = LOG_PATH.open("w", encoding="utf-8")
    sys.stdout = Tee(sys.__stdout__, log)
    sys.stderr = Tee(sys.__stderr__, log)
    print(f"Build started: {datetime.now(timezone.utc).isoformat()}", flush=True)
    return log


def run_command(args: list[str], *, check: bool = True, cwd: Path = ROOT) -> int:
    """Stream combined output line-by-line; never hide a long-running command."""
    print("+", subprocess.list2cmdline(args), flush=True)
    process = subprocess.Popen(
        args,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        bufsize=1,
    )
    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="", flush=True)
    return_code = process.wait()
    if check and return_code:
        raise subprocess.CalledProcessError(return_code, args)
    return return_code


def package_version(name: str) -> str:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return "not installed"


def android_scaffolds() -> list[Path]:
    """Return Briefcase Android scaffold roots containing the Gradle project."""
    if not BUILD.exists():
        return []
    roots = {path.parent for path in BUILD.glob("*/android/gradle") if path.is_dir()}
    roots.update(path for path in BUILD.glob("*/android") if (path / "gradle").is_dir())
    return sorted(roots)


def gradle_projects() -> list[Path]:
    """Return Gradle roots generated by Briefcase, without assuming an app ID."""
    if not BUILD.exists():
        return []
    return sorted(
        {path.parent for path in BUILD.rglob("gradlew")}.union(
            path.parent for path in BUILD.rglob("gradlew.bat")
        )
    )


def clean_android() -> None:
    android_trees = (
        sorted(path for path in BUILD.glob("*/android") if path.is_dir())
        if BUILD.exists()
        else []
    )
    for tree in android_trees:
        print(f"Removing Android scaffold/cache: {tree}", flush=True)
        shutil.rmtree(tree)
    shutil.rmtree(ANDROID_RELEASE, ignore_errors=True)


def find_apks(suffix: str | None = None) -> list[Path]:
    """Search Briefcase output recursively; no fixed Gradle output path assumptions."""
    if not BUILD.exists():
        return []
    pattern = f"*{suffix}.apk" if suffix else "*.apk"
    return sorted(BUILD.rglob(pattern), key=lambda path: path.stat().st_mtime)


def find_android_tool(name: str) -> str | None:
    direct = shutil.which(name)
    if direct:
        return direct
    executable = f"{name}.exe" if os.name == "nt" else name
    for variable in ("ANDROID_HOME", "ANDROID_SDK_ROOT"):
        sdk = os.environ.get(variable)
        if not sdk:
            continue
        candidates = sorted(
            (Path(sdk) / "build-tools").glob(f"*/{executable}"), reverse=True
        )
        if candidates:
            return str(candidates[0])
    return None


def embedded_signature_exists(apk: Path) -> bool:
    """Detect JAR (v1) or APK Signing Block (v2+) signatures."""
    data = apk.read_bytes()
    if b"APK Sig Block 42" in data:
        return True
    try:
        with zipfile.ZipFile(apk) as archive:
            names = {name.upper() for name in archive.namelist()}
    except zipfile.BadZipFile:
        return False
    signature_files = any(
        name.startswith("META-INF/") and name.endswith((".RSA", ".DSA", ".EC"))
        for name in names
    )
    return signature_files and any(
        name.startswith("META-INF/") and name.endswith(".SF") for name in names
    )


def inspect_apk(apk: Path) -> ApkInspection:
    complete = False
    abis: list[str] = []
    details = ""
    try:
        with zipfile.ZipFile(apk) as archive:
            names = archive.namelist()
            complete = "AndroidManifest.xml" in names and "classes.dex" in names
            abis = sorted(
                {
                    name.split("/")[1]
                    for name in names
                    if name.startswith("lib/") and name.count("/") >= 2
                }
            )
    except (OSError, zipfile.BadZipFile) as exc:
        details = str(exc)
    signed = embedded_signature_exists(apk) if complete else False
    apksigner = find_android_tool("apksigner")
    if not apksigner:
        return ApkInspection(
            complete, signed, abis, "SIGNATURE VERIFY TOOL NOT AVAILABLE", details
        )
    result = subprocess.run(
        [apksigner, "verify", "--verbose", "--print-certs", str(apk)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    output = "\n".join(
        part.strip() for part in (result.stdout, result.stderr) if part.strip()
    )
    if output:
        print(output, flush=True)
    return ApkInspection(
        complete,
        signed and result.returncode == 0,
        abis,
        "PASS" if result.returncode == 0 else "FAIL",
        output,
    )


def is_installable(inspection: ApkInspection) -> bool:
    """An APK is installable only when its required contents and signature exist."""
    return inspection.complete and inspection.signed


def artifact_name(kind: str, *, signed: bool = False) -> str:
    if kind == "debug":
        return f"{APP_FILENAME}-{APP_VERSION}-debug.apk"
    suffix = "release" if signed else "release-unsigned"
    return f"{APP_FILENAME}-{APP_VERSION}-{suffix}.apk"


def copy_apk(source: Path, kind: str, *, signed: bool = False) -> tuple[Path, int, str]:
    destination = ANDROID_RELEASE / artifact_name(kind, signed=signed)
    ANDROID_RELEASE.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    size = destination.stat().st_size
    digest = hashlib.sha256(destination.read_bytes()).hexdigest()
    print(f"APK type: {kind}")
    print(f"APK created: {destination.resolve()}")
    print(f"Size: {size / 1048576:.2f} MB")
    print(f"SHA256: {digest}")
    if size / 1048576 > BUILD_SIZE_WARNING_MB:
        print("WARNING: APK is larger than the configured size warning threshold.")
    return destination, size, digest


def write_report(state: dict[str, str]) -> None:
    RELEASE.mkdir(parents=True, exist_ok=True)
    lines = [
        f"Build Date: {datetime.now(timezone.utc).isoformat()}",
        f"APP Version: {APP_VERSION}",
        f"Python Version: {platform.python_version()}",
        f"Briefcase Version: {package_version('briefcase')}",
        f"Toga Version: {package_version('toga')}",
        f"Platform: {platform.platform()}",
        f"pytest result: {state.get('tests', 'NOT RUN')}",
        f"Android create/update result: {state.get('scaffold', 'NOT RUN')}",
        f"Android build result: {state.get('build', 'NOT RUN')}",
        f"Android package result: {state.get('package', 'NOT RUN')}",
        f"APK Type: {state.get('apk_type', 'N/A')}",
        f"Signed: {state.get('signed', 'NO')}",
        f"Installable: {state.get('installable', 'NO')}",
        f"INSTALLABLE APK: {state.get('installable', 'NO')}",
        f"ABI: {state.get('abi', 'N/A')}",
        f"APK path: {state.get('apk_path', 'N/A')}",
        f"APK Size: {state.get('apk_size', 'N/A')}",
        f"Signature Verification: {state.get('signature_verification', 'NOT RUN')}",
        f"SHA256: {state.get('sha256', 'N/A')}",
        f"Error: {state.get('error', 'N/A')}",
        f"FINAL STATUS: {state.get('final', 'FAIL')}",
    ]
    (RELEASE / "build_report.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate_configuration() -> None:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    backend = data.get("build-system", {}).get("build-backend")
    if backend != "setuptools.build_meta":
        raise RuntimeError(
            f"Unsupported Python build backend: {backend!r}. Expected setuptools.build_meta."
        )
    app = data["tool"]["briefcase"]["app"]["worktime_tracker"]
    if "src/worktime_tracker" not in app["sources"]:
        raise RuntimeError("Briefcase sources must include src/worktime_tracker.")
    if "android" not in app:
        raise RuntimeError("Briefcase Android configuration is missing.")
    android = app["android"]
    if MATERIAL_DEPENDENCY not in android.get("build_gradle_dependencies", []):
        raise RuntimeError(
            f"OptionContainer requires Android Gradle dependency {MATERIAL_DEPENDENCY}."
        )
    policy = json.loads(BACKUP_POLICY.read_text(encoding="utf-8"))
    if policy.get("application_attributes", {}).get("allowBackup") != "false":
        raise RuntimeError("Android backup policy must set allowBackup to false.")
    for rules in (BACKUP_RULES, BACKUP_RULES_LEGACY):
        ET.parse(rules)


def validate_generated_gradle_dependencies() -> None:
    """Confirm Briefcase persisted required Maven dependencies into Gradle."""
    gradle_files = (
        sorted([*BUILD.rglob("build.gradle"), *BUILD.rglob("build.gradle.kts")])
        if BUILD.exists()
        else []
    )
    app_gradle_files = [path for path in gradle_files if path.parent.name == "app"]
    if not app_gradle_files:
        raise RuntimeError("Generated Android app/build.gradle was not found.")
    if not any(
        MATERIAL_DEPENDENCY in path.read_text(encoding="utf-8")
        for path in app_gradle_files
    ):
        locations = ", ".join(str(path) for path in app_gradle_files)
        raise RuntimeError(
            f"Generated Gradle is missing {MATERIAL_DEPENDENCY}: {locations}"
        )
    print(
        f"Android Gradle dependency verified: implementation '{MATERIAL_DEPENDENCY}'",
        flush=True,
    )


def android_manifests() -> list[Path]:
    """Find generated application manifests without assuming an app folder name."""
    if not BUILD.exists():
        return []
    return sorted(
        path
        for path in BUILD.rglob("AndroidManifest.xml")
        if path.parent.name == "main" and path.parent.parent.name == "src"
    )


def configure_android_backup_policy() -> None:
    """Reapply the repository-owned policy after every Briefcase create/update."""
    attributes = json.loads(BACKUP_POLICY.read_text(encoding="utf-8"))[
        "application_attributes"
    ]
    manifests = android_manifests()
    if not manifests:
        raise RuntimeError("Generated Android application manifest was not found.")
    ET.register_namespace("android", ANDROID_NAMESPACE)
    for manifest in manifests:
        tree = ET.parse(manifest)
        application = tree.getroot().find("application")
        if application is None:
            raise RuntimeError(
                f"Android manifest has no application element: {manifest}"
            )
        for name, value in attributes.items():
            application.set(f"{{{ANDROID_NAMESPACE}}}{name}", value)
        resource_directory = manifest.parent / "res" / "xml"
        resource_directory.mkdir(parents=True, exist_ok=True)
        shutil.copy2(BACKUP_RULES, resource_directory / BACKUP_RULES.name)
        shutil.copy2(
            BACKUP_RULES_LEGACY,
            resource_directory / BACKUP_RULES_LEGACY.name,
        )
        tree.write(manifest, encoding="utf-8", xml_declaration=True)
    validate_android_backup_policy()


def validate_android_backup_policy() -> None:
    expected = json.loads(BACKUP_POLICY.read_text(encoding="utf-8"))[
        "application_attributes"
    ]
    for manifest in android_manifests():
        application = ET.parse(manifest).getroot().find("application")
        if application is None or any(
            application.get(f"{{{ANDROID_NAMESPACE}}}{name}") != value
            for name, value in expected.items()
        ):
            raise RuntimeError(f"Android automatic backup is not disabled: {manifest}")
        resource_directory = manifest.parent / "res" / "xml"
        for rules in (BACKUP_RULES, BACKUP_RULES_LEGACY):
            generated = resource_directory / rules.name
            if not generated.is_file() or generated.read_bytes() != rules.read_bytes():
                raise RuntimeError(
                    f"Generated Android backup rules are missing: {generated}"
                )
    print("Android Auto Backup/Restore policy verified: DISABLED", flush=True)


def doctor() -> int:
    """Report prerequisites without rejecting Briefcase-managed Java or Android SDK."""
    validate_configuration()
    java = shutil.which("java")
    briefcase_installed = package_version("briefcase") != "not installed"
    print(f"Python executable: {sys.executable}")
    print(f"Python version: {platform.python_version()}")
    print(f"Project root: {ROOT}")
    print(
        f"Virtual environment: {sys.prefix != getattr(sys, 'base_prefix', sys.prefix)} ({sys.prefix})"
    )
    print(f"Briefcase version: {package_version('briefcase')}")
    print(f"Java availability: {java or 'not found on PATH'}")
    print(f"JAVA_HOME: {os.environ.get('JAVA_HOME', 'not set')}")
    print(
        f"Android SDK availability: {os.environ.get('ANDROID_HOME') or os.environ.get('ANDROID_SDK_ROOT') or 'not set'}"
    )
    print(f"ANDROID_HOME: {os.environ.get('ANDROID_HOME', 'not set')}")
    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    print(f"pyproject.toml: {(ROOT / 'pyproject.toml').is_file()}")
    print(f"Python build backend: {pyproject['build-system']['build-backend']}")
    print(f"Android scaffold: {android_scaffolds() or 'not created'}")
    print(f"Release directory: {RELEASE}")
    if java:
        print("System Java detected (Android builds require JDK 17):")
        run_command([java, "-version"], check=False)
    else:
        print("Briefcase-managed Java/Android SDK will be used when available.")
    if briefcase_installed:
        run_command([sys.executable, "-m", "briefcase", "--version"], check=False)
    else:
        print("Briefcase is not installed in this Python environment.")
    return 0


def run_gradle_debug() -> None:
    java_home = os.environ.get("JAVA_HOME")
    java_name = "java.exe" if os.name == "nt" else "java"
    java_from_home = Path(java_home) / "bin" / java_name if java_home else None
    if java_from_home and not java_from_home.is_file():
        raise RuntimeError(
            f"Gradle fallback cannot run because JAVA_HOME is invalid: {java_home}"
        )
    if not java_from_home and not shutil.which("java"):
        raise RuntimeError(
            "Gradle fallback requires JAVA_HOME or a java executable on PATH. "
            "Briefcase did not produce a debug APK."
        )
    projects = gradle_projects()
    if not projects:
        raise RuntimeError(
            "Briefcase Android Gradle project was not found after create/update."
        )
    project = projects[-1]
    wrapper = project / ("gradlew.bat" if os.name == "nt" else "gradlew")
    command = [str(wrapper), "assembleDebug"]
    run_command(command, cwd=project)


def obtain_debug_apk() -> Path:
    """Use Briefcase's debug artifact, falling back to Gradle only when absent."""
    candidates = find_apks("-debug")
    if candidates:
        apk = candidates[-1]
        print(f"[PACKAGE] Using Debug APK produced by Briefcase: {apk}", flush=True)
        return apk

    print(
        "[PACKAGE] Briefcase produced no Debug APK; falling back to Gradle assembleDebug.",
        flush=True,
    )
    run_gradle_debug()
    candidates = find_apks("-debug")
    if not candidates:
        raise RuntimeError(
            "Gradle assembleDebug completed but no newly generated *-debug.apk was found."
        )
    return candidates[-1]


def release_signing_configured() -> bool:
    return all(os.environ.get(name) for name in SIGNING_ENV_VARS)


def sign_release_apk(unsigned_apk: Path) -> Path:
    apksigner = find_android_tool("apksigner")
    if not apksigner:
        raise RuntimeError(
            "Release signing is configured, but apksigner is unavailable."
        )
    keystore = Path(os.environ["ANDROID_KEYSTORE"]).expanduser()
    if not keystore.is_file():
        raise RuntimeError(f"Release keystore was not found: {keystore}")
    signed_apk = ANDROID_RELEASE / artifact_name("release", signed=True)
    shutil.copy2(unsigned_apk, signed_apk)
    run_command(
        [
            apksigner,
            "sign",
            "--ks",
            str(keystore),
            "--ks-key-alias",
            os.environ["ANDROID_KEY_ALIAS"],
            "--ks-pass",
            "env:ANDROID_KEYSTORE_PASSWORD",
            "--key-pass",
            "env:ANDROID_KEY_PASSWORD",
            str(signed_apk),
        ]
    )
    return signed_apk


def print_debug_ready(apk: Path, size: int) -> None:
    print("=" * 40)
    print("ANDROID DEBUG APK READY")
    print(f"File:\n{apk.relative_to(ROOT)}")
    print("Signed:\nYES")
    print("Installable:\nYES")
    print(f"Size:\n{size / 1048576:.2f} MB")
    print("=" * 40)
    print("請將此 debug APK 傳到 Android 手機進行安裝。")


def build_android(
    clean: bool,
    mode: str = "debug",
    require_release_signing: bool = False,
) -> int:
    state: dict[str, str] = {"final": "FAIL"}
    try:
        validate_configuration()
        if (
            mode == "release"
            and require_release_signing
            and not release_signing_configured()
        ):
            missing = ", ".join(
                name for name in SIGNING_ENV_VARS if not os.environ.get(name)
            )
            raise RuntimeError(
                f"Release signing is not configured. Set keystore credentials outside Git: {missing}"
            )
        if clean:
            clean_android()
        print("[TEST] Running project tests...", flush=True)
        state["tests"] = "FAIL"
        run_command([sys.executable, "-m", "pytest", "-q"])
        state["tests"] = "PASS"
        if android_scaffolds():
            print(
                "[UPDATE] Existing Android scaffold found; running Briefcase update.",
                flush=True,
            )
            state["scaffold"] = "UPDATE FAIL"
            run_command([sys.executable, "-m", "briefcase", "update", "android"])
            state["scaffold"] = "UPDATE PASS"
        else:
            print(
                "[CREATE] No Android scaffold found; running Briefcase create once.",
                flush=True,
            )
            state["scaffold"] = "CREATE FAIL"
            run_command([sys.executable, "-m", "briefcase", "create", "android"])
            state["scaffold"] = "CREATE PASS"
        configure_android_backup_policy()
        validate_generated_gradle_dependencies()
        print(f"[BUILD] Building Android {mode} application...", flush=True)
        state["build"] = "FAIL"
        run_command([sys.executable, "-m", "briefcase", "build", "android"])
        state["build"] = "PASS"
        state["package"] = "FAIL"
        if mode == "debug":
            apk, size, digest = copy_apk(obtain_debug_apk(), "debug")
        else:
            package_started = datetime.now().timestamp()
            print("[PACKAGE] Packaging release APK and AAB...", flush=True)
            run_command(
                [sys.executable, "-m", "briefcase", "package", "android", "-p", "apk"]
            )
            candidates = [
                path
                for path in find_apks()
                if "debug" not in path.name.lower()
                and path.stat().st_mtime >= package_started - 2
            ]
            if not candidates:
                raise RuntimeError(
                    "Release package completed but no newly generated release APK was found."
                )
            unsigned_apk, _, _ = copy_apk(candidates[-1], "release", signed=False)
            apk = (
                sign_release_apk(unsigned_apk)
                if release_signing_configured()
                else unsigned_apk
            )
            size = apk.stat().st_size
            digest = hashlib.sha256(apk.read_bytes()).hexdigest()
            if not release_signing_configured():
                print("UNSIGNED RELEASE APK", flush=True)
            try:
                run_command(
                    [
                        sys.executable,
                        "-m",
                        "briefcase",
                        "package",
                        "android",
                        "-p",
                        "aab",
                    ]
                )
                aabs = sorted(
                    BUILD.rglob("*.aab"), key=lambda path: path.stat().st_mtime
                )
                if aabs:
                    ANDROID_RELEASE.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(
                        aabs[-1], ANDROID_RELEASE / f"{APP_FILENAME}-{APP_VERSION}.aab"
                    )
            except subprocess.CalledProcessError:
                print(
                    "WARNING: AAB packaging failed; APK status will still be reported."
                )
        state["package"] = "PASS"
        inspection = inspect_apk(apk)
        installable = is_installable(inspection)
        state.update(
            apk_type=mode.upper(),
            signed="YES" if inspection.signed else "NO",
            installable="YES" if installable else "NO",
            abi="\n".join(inspection.abis) or "N/A",
            apk_path=str(apk.resolve()),
            apk_size=f"{size / 1048576:.2f} MB",
            sha256=digest,
            signature_verification=inspection.signature_verification,
        )
        if mode == "debug" and not installable:
            raise RuntimeError(
                "Debug APK is incomplete or unsigned and cannot be installed."
            )
        state["final"] = "PASS"
        write_report(state)
        if mode == "debug":
            print_debug_ready(apk, size)
        return 0
    except Exception as exc:
        state["error"] = str(exc)
        write_report(state)
        print(f"BUILD FAILED: {exc}", file=sys.stderr, flush=True)
        return 1


def ios_scaffolds() -> list[Path]:
    if not BUILD.exists():
        return []
    return sorted(path for path in BUILD.glob("*/iOS") if path.is_dir())


def build_ios() -> int:
    """Retain the macOS Briefcase iOS path; signing remains an Xcode task."""
    if platform.system() != "Darwin":
        print("iOS builds require macOS and Xcode.", file=sys.stderr)
        return 1
    try:
        command = "update" if ios_scaffolds() else "create"
        run_command([sys.executable, "-m", "briefcase", command, "iOS"])
        run_command([sys.executable, "-m", "briefcase", "build", "iOS"])
        run_command([sys.executable, "-m", "briefcase", "package", "iOS"])
        return 0
    except Exception as exc:
        print(f"iOS BUILD FAILED: {exc}", file=sys.stderr)
        return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="WorkTime Tracker mobile build tool")
    parser.add_argument(
        "action",
        choices=("android", "ios", "all", "test", "clean", "doctor"),
        nargs="?",
        default="android",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove Android scaffold/cache before rebuilding",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--debug",
        action="store_const",
        const="debug",
        dest="mode",
        help="Build a signed debug APK (default)",
    )
    mode.add_argument(
        "--release",
        action="store_const",
        const="release",
        dest="mode",
        help="Build release APK/AAB artifacts",
    )
    parser.set_defaults(mode="debug")
    parser.add_argument(
        "--require-release-signing", action="store_true", help=argparse.SUPPRESS
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.action == "doctor":
        return doctor()
    if args.action == "test":
        return run_command([sys.executable, "-m", "pytest", "-q"], check=False)
    if args.action == "clean":
        clean_android()
        return 0
    if args.action == "android":
        return build_android(args.clean, args.mode, args.require_release_signing)
    if args.action == "ios":
        return build_ios()
    if args.action == "all":
        android_result = build_android(
            args.clean, args.mode, args.require_release_signing
        )
        return android_result or build_ios()
    return 2


if __name__ == "__main__":
    log_handle = enable_logging()
    try:
        exit_code = main()
    finally:
        sys.stdout = sys.__stdout__
        sys.stderr = sys.__stderr__
        log_handle.close()
    raise SystemExit(exit_code)
