import type {BackupData,BackupManifest} from './backupTypes'
export class BackupValidationError extends Error{}
const fail=(message:string):never=>{throw new BackupValidationError(message)}
const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const integer=(v:unknown,min=0):v is number=>typeof v==='number'&&Number.isFinite(v)&&Number.isInteger(v)&&v>=min
const date=(v:unknown):v is string=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const [y,m,d]=v.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()+1===m&&x.getUTCDate()===d}
const time=(v:unknown)=>v===null||v===undefined||(typeof v==='string'&&/^(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/.test(v))
const iso=(v:unknown)=>typeof v==='string'&&!Number.isNaN(Date.parse(v))
function columns(row:Record<string,unknown>,allowed:string[],required:string[],label:string){if(required.some(k=>!(k in row))||Object.keys(row).some(k=>!allowed.includes(k)))fail(`備份的 ${label} 欄位無效。`)}
const specs:Record<string,{a:string[];r:string[]}>= {
 work_records:{a:['id','work_date','clock_in','clock_out','break_start','break_end','deduct_break','standard_minutes','note','workday_type','overnight'],r:['id','work_date','clock_in','clock_out']},settings:{a:['key','value','effective_date'],r:['key','value']},leave_cycles:{a:['id','start_date','end_date','total_minutes'],r:['id','start_date','end_date','total_minutes']},comp_leave_cycles:{a:['id','start_date','end_date'],r:['id','start_date','end_date']},comp_settlement_policy_history:{a:['id','effective_from','mode','monthly_cap_minutes','cash_hourly_rate_cents','created_at'],r:['id','effective_from','mode','monthly_cap_minutes','cash_hourly_rate_cents','created_at']},monthly_settlements:{a:['id','year','month','minutes','rule'],r:['id','year','month','minutes','rule']},app_metadata:{a:['key','value'],r:['key','value']},calendar_overrides:{a:['id','work_date','day_type','note','created_at','updated_at'],r:['id','work_date','day_type']},official_holidays:{a:['holiday_date','name','year','source','synced_at'],r:['holiday_date','name','year','source','synced_at']}}
const ledgerAllowed=['id','entry_date','entry_type','reason','comp_change','annual_change','comp_balance','annual_balance','source_record_id','transaction_datetime','transaction_type','ledger_origin','source_leave_type','target_leave_type','source_minutes','target_minutes','note','created_at','reversal_of_id','monthly_comp_balance','annual_comp_balance','cash_amount_cents','cash_hourly_rate_cents']
const tx=new Set(['WORKTIME_EARN','WORKTIME_DEDUCTION','MONTHLY_SETTLEMENT','LEAVE_CONVERSION','REVERSAL','ADJUSTMENT','MISSING_WORKDAY_DEDUCTION','ANNUAL_LEAVE_GRANT','ANNUAL_LEAVE_SETTLEMENT','COMP_LEAVE_SETTLEMENT','COMP_MONTHLY_TRANSFER','COMP_MONTHLY_CASH_SETTLEMENT']),workdays=new Set(['正常工作日','休息日','假日','補休','特休','其他']),leaves=new Set(['COMP_TIME','ANNUAL_LEAVE'])
export function validateManifest(v:unknown):BackupManifest{if(!object(v))throw new BackupValidationError('備份 manifest 格式無效。');if(v.format_name!=='WorkTimeTrackerBackup')fail('不是工時管家備份檔。');if(v.backup_format_version!==1&&v.backup_format_version!==2)fail('不支援的備份格式版本。');if(typeof v.app_version!=='string'||!iso(v.created_at)||!integer(v.database_schema_version)||!integer(v.record_count)||typeof v.data_sha256!=='string'||!/^[a-f\d]{64}$/i.test(v.data_sha256))fail('備份 manifest 欄位無效。');return {format_name:String(v.format_name),backup_format_version:Number(v.backup_format_version),app_version:String(v.app_version),created_at:String(v.created_at),database_schema_version:Number(v.database_schema_version),record_count:Number(v.record_count),data_sha256:String(v.data_sha256)}}
export function validateData(v:unknown,version:number):BackupData{if(!object(v))throw new BackupValidationError('備份缺少必要資料欄位。');const root=v;if(!object(root.tables))throw new BackupValidationError('備份缺少必要資料欄位。');const tables=root.tables;if(!Array.isArray(tables.work_records)||!Array.isArray(tables.settings)||!Array.isArray(root.manual_ledger_events))throw new BackupValidationError('備份缺少必要資料欄位。');for(const [name,s] of Object.entries(specs)){const optional=(version===1&&['calendar_overrides','official_holidays'].includes(name))||['comp_leave_cycles','comp_settlement_policy_history'].includes(name);const rows=tables[name]??(optional?[]:undefined);if(!Array.isArray(rows))throw new BackupValidationError(`備份的 ${name} 欄位無效。`);for(const value of rows){if(!object(value))fail(`備份的 ${name} 欄位無效。`);columns(value,s.a,s.r,name);validateRow(name,value)}}
 const dates=new Set<string>(),ids=new Set<number>();for(const r of tables.work_records){const row=r as Record<string,unknown>;if(dates.has(row.work_date as string)||ids.has(row.id as number))fail('備份的工時日期或 ID 無效或重複。');dates.add(row.work_date as string);ids.add(row.id as number)}
 const manualIds=new Set<number>();for(const value of root.manual_ledger_events){if(!object(value))fail('備份的手動 Ledger 欄位無效。');columns(value,ledgerAllowed,['id','entry_date','entry_type','reason','transaction_datetime','transaction_type','ledger_origin','created_at'],'手動 Ledger');if(!integer(value.id,1)||manualIds.has(value.id)||!date(value.entry_date)||!iso(value.transaction_datetime)||!iso(value.created_at)||value.ledger_origin!=='MANUAL'||!tx.has(String(value.transaction_type)))fail('備份的手動 Ledger 欄位無效。');for(const k of ['comp_change','annual_change','comp_balance','annual_balance','source_minutes','target_minutes','monthly_comp_balance','annual_comp_balance','cash_amount_cents','cash_hourly_rate_cents'])if(value[k]!==undefined&&value[k]!==null&&!integer(value[k],k.includes('change')?-Number.MAX_SAFE_INTEGER:0))fail('備份的手動 Ledger數值無效。');if(value.source_leave_type!=null&&!leaves.has(String(value.source_leave_type))||value.target_leave_type!=null&&!leaves.has(String(value.target_leave_type)))fail('備份的假別類型無效。');manualIds.add(value.id)}
 const reversed=new Set<number>();for(const value of root.manual_ledger_events as Record<string,unknown>[]){if(value.transaction_type==='REVERSAL'){const id=value.reversal_of_id;if(!integer(id,1)||reversed.has(id as number))fail('備份的撤銷關聯無效或重複。');const target=(root.manual_ledger_events as Record<string,unknown>[]).find(x=>x.id===id);if(!target||target.transaction_type!=='LEAVE_CONVERSION'||target.ledger_origin!=='MANUAL')fail('備份的撤銷關聯找不到原始轉換。');reversed.add(id as number)}}
 if(!('calendar_overrides' in tables))tables.calendar_overrides=[];if(!('official_holidays' in tables))tables.official_holidays=[];if(!('comp_leave_cycles' in tables))tables.comp_leave_cycles=[];if(!('comp_settlement_policy_history' in tables))tables.comp_settlement_policy_history=[];
 const ext=root.pwa_extensions;if(ext!==undefined){if(!object(ext)||Object.keys(ext).some(k=>!['calendar_override_categories','comp_daily_cap_policies','producer'].includes(k))||ext.producer!==undefined&&ext.producer!=='PWA'||ext.calendar_override_categories!==undefined&&!object(ext.calendar_override_categories)||ext.comp_daily_cap_policies!==undefined&&!object(ext.comp_daily_cap_policies))fail('PWA 擴充資料無效。')}
 if(object(ext)&&object(ext.comp_daily_cap_policies))for(const [effectiveFrom,value] of Object.entries(ext.comp_daily_cap_policies)){if(!date(effectiveFrom)||!object(value)||Object.keys(value).some(k=>!['enabled','daily_cap_minutes'].includes(k))||typeof value.enabled!=='boolean'||!integer(value.daily_cap_minutes,1)||value.daily_cap_minutes>1440)fail('PWA 每日補休上限擴充資料無效。')}
 return root as unknown as BackupData}
function validateRow(name:string,r:Record<string,unknown>){if('id'in r&&!integer(r.id,1))fail(`備份的 ${name} ID 無效。`);for(const k of ['work_date','start_date','end_date','effective_from','holiday_date'])if(k in r&&!date(r[k]))fail(`備份的 ${name} 日期無效。`);if(name==='work_records'){if(!time(r.clock_in)||!time(r.clock_out)||!time(r.break_start)||!time(r.break_end)||!integer(r.standard_minutes??480)||!workdays.has(String(r.workday_type??'正常工作日'))||![true,false,0,1].includes(r.deduct_break as boolean)||![true,false,0,1].includes(r.overnight as boolean))fail('備份的 work_records 資料無效。')}if(name==='calendar_overrides'&&!['WORKDAY','NON_WORKDAY'].includes(String(r.day_type)))fail('備份的 calendar_overrides 類型無效。');if(name==='comp_settlement_policy_history'&&(!['ANNUAL','MONTHLY'].includes(String(r.mode))||!integer(r.monthly_cap_minutes)||!integer(r.cash_hourly_rate_cents)||!iso(r.created_at)))fail('備份的補休政策無效。');if(name==='monthly_settlements'&&(!integer(r.year)||!integer(r.month,1)||(r.month as number)>12||!integer(r.minutes,-Number.MAX_SAFE_INTEGER)))fail('備份的 monthly_settlements 無效。')}
