import type {CompMonthlySettlement,CompSettlementPolicy,DeductionPriority,ISODate,LedgerEntry,LeaveCycle,WorkRecord} from '../models/domain'
import type {LedgerRepository} from '../repositories/contracts'
import {calculateWorkMinutes} from './workTimeService'
import {CalendarService,localISODate} from './calendarService'

export const LEDGER_CHANGED='ledger-changed'
export const ledgerEvents=new EventTarget()
export interface ReplayInput{records:WorkRecord[];manualEntries?:LedgerEntry[];calendar:CalendarService;dailyStandardMinutes:number;trackingStartDate:ISODate;today:ISODate;priority:DeductionPriority;annualCycles:LeaveCycle[];compCycles?:LeaveCycle[];compPolicies?:CompSettlementPolicy[];currentCompCycleStart?:ISODate;activationDate:ISODate;legacyAnnualOpening?:number}
export interface ReplayResult{entries:LedgerEntry[];settlements:CompMonthlySettlement[]}
const stamp=(date:string,time:string)=>`${date}T${time}`
const created='1970-01-01T00:00:00.000Z'
const base=(entry:Partial<LedgerEntry>&Pick<LedgerEntry,'entryDate'|'entryType'|'reason'|'transactionDatetime'|'transactionType'|'ledgerOrigin'>):LedgerEntry=>({compChange:0,annualChange:0,compBalance:0,annualBalance:0,note:'',createdAt:created,monthlyCompBalance:0,annualCompBalance:0,cashAmountCents:0,cashHourlyRateCents:0,...entry})
const defaultPolicy=(effectiveFrom:ISODate):CompSettlementPolicy=>({effectiveFrom,mode:'ANNUAL',monthlyCapMinutes:2400,cashHourlyRateCents:0,dailyCapEnabled:false,dailyCapMinutes:720,createdAt:created})
export function normalizeCompPolicy(policy:CompSettlementPolicy):CompSettlementPolicy{return {...policy,dailyCapEnabled:policy.dailyCapEnabled??false,dailyCapMinutes:policy.dailyCapMinutes??720}}
export function calculateDailyCompEarning(actualMinutes:number,standardMinutes:number,dailyCapEnabled:boolean,dailyCapMinutes:number){
  const shortfallMinutes=Math.max(standardMinutes-actualMinutes,0)
  if(shortfallMinutes)return {compEarnMinutes:0,shortfallMinutes,excessSettlementMinutes:0}
  if(!dailyCapEnabled)return {compEarnMinutes:actualMinutes-standardMinutes,shortfallMinutes:0,excessSettlementMinutes:0}
  return {compEarnMinutes:Math.max(Math.min(actualMinutes,dailyCapMinutes)-standardMinutes,0),shortfallMinutes:0,excessSettlementMinutes:Math.max(actualMinutes-dailyCapMinutes,0)}
}
export function cashAmountCents(minutes:number,rateCents:number){return Math.floor((minutes*rateCents+30)/60)}
export function deductLeave(shortfall:number,comp:number,annual:number,priority:DeductionPriority):[number,number]{let remaining=Math.max(0,shortfall),cc=0,ac=0;const useComp=()=>{const used=Math.min(Math.max(comp,0),remaining);cc-=used;remaining-=used},useAnnual=()=>{const used=Math.min(Math.max(annual,0),remaining);ac-=used;remaining-=used};if(priority==='COMP_TIME_FIRST'){useComp();useAnnual();if(remaining)ac-=remaining}else{useAnnual();useComp();if(remaining)cc-=remaining}return[cc,ac]}
function dates(start:ISODate,end:ISODate):ISODate[]{const out:ISODate[]=[];let [y,m,d]=start.split('-').map(Number),cursor=new Date(Date.UTC(y,m-1,d)),stop=new Date(`${end}T00:00:00Z`);while(cursor<=stop){out.push(`${cursor.getUTCFullYear()}-${String(cursor.getUTCMonth()+1).padStart(2,'0')}-${String(cursor.getUTCDate()).padStart(2,'0')}` as ISODate);cursor.setUTCDate(cursor.getUTCDate()+1)}return out}
function monthEnd(value:ISODate):ISODate{const y=Number(value.slice(0,4)),m=Number(value.slice(5,7)),d=new Date(Date.UTC(y,m,0)).getUTCDate();return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}` as ISODate}
function nextMonthStart(value:ISODate):ISODate{const y=Number(value.slice(0,4)),m=Number(value.slice(5,7)),d=new Date(Date.UTC(y,m,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-01` as ISODate}

export function replayLedgerWithSettlements(input:ReplayInput):ReplayResult{
  const policies=[...(input.compPolicies??[])].map(normalizeCompPolicy).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom)||a.createdAt.localeCompare(b.createdAt)),policyOn=(day:ISODate)=>policies.filter(p=>p.effectiveFrom<=day).at(-1)??defaultPolicy(day)
  const events:LedgerEntry[]=(input.manualEntries??[]).filter(e=>e.ledgerOrigin==='MANUAL').map(e=>({...e}))
  if(input.legacyAnnualOpening)events.push(base({entryDate:input.annualCycles[0]?.startDate??input.activationDate,entryType:'年度期初',reason:'年度假別設定',annualChange:input.legacyAnnualOpening,transactionDatetime:stamp(input.annualCycles[0]?.startDate??input.activationDate,'00:00:00'),transactionType:'ADJUSTMENT',ledgerOrigin:'SYSTEM'}))
  for(const cycle of input.annualCycles){if(input.activationDate<=cycle.startDate&&cycle.startDate<=input.today)events.push(base({entryDate:cycle.startDate,entryType:'特休年度核給',reason:`${cycle.startDate.replaceAll('-','/')}～${cycle.endDate.replaceAll('-','/')}`,annualChange:cycle.totalMinutes??0,transactionDatetime:stamp(cycle.startDate,'00:00:00'),transactionType:'ANNUAL_LEAVE_GRANT',ledgerOrigin:'SYSTEM'}));if(input.activationDate<=cycle.endDate&&cycle.endDate<input.today)events.push(base({entryDate:cycle.endDate,entryType:'特休年度結算',reason:`結算 ${cycle.startDate.replaceAll('-','/')}～${cycle.endDate.replaceAll('-','/')}`,transactionDatetime:stamp(cycle.endDate,'23:59:59'),transactionType:'ANNUAL_LEAVE_SETTLEMENT',ledgerOrigin:'SYSTEM'}))}
  const records=new Map(input.records.map(r=>[r.workDate,r]));for(const record of input.records){if(record.workDate>input.today)continue;const actual=calculateWorkMinutes(record),standard=input.calendar.standardMinutesFor(record.workDate,input.dailyStandardMinutes),policy=policyOn(record.workDate),earning=calculateDailyCompEarning(actual,standard,policy.dailyCapEnabled,policy.dailyCapMinutes),difference=actual-standard;events.push(base({entryDate:record.workDate,entryType:standard===0&&actual>0?'假日工作':difference>=0?'正常工作':'工時不足',reason:standard===0&&actual>0?input.calendar.getWorkdayReason(record.workDate).label:'依每日工時重新計算',compChange:earning.compEarnMinutes,sourceRecordId:record.id,transactionDatetime:stamp(record.workDate,'18:00:00'),transactionType:difference>=0?'WORKTIME_EARN':'WORKTIME_DEDUCTION',ledgerOrigin:'SYSTEM'}));if(earning.excessSettlementMinutes)events.push(base({entryDate:record.workDate,entryType:'每日超額待結算',reason:'超過每日補休計算上限',sourceRecordId:record.id,sourceMinutes:earning.excessSettlementMinutes,transactionDatetime:stamp(record.workDate,'18:00:30'),transactionType:'COMP_DAILY_EXCESS_ACCRUAL',ledgerOrigin:'SYSTEM'}))}
  for(const cycle of input.compCycles??[])if(input.activationDate<=cycle.endDate&&cycle.endDate<input.today){const sourceMinutes=events.filter(e=>e.transactionType==='COMP_DAILY_EXCESS_ACCRUAL'&&e.entryDate>=cycle.startDate&&e.entryDate<=cycle.endDate).reduce((sum,e)=>sum+(e.sourceMinutes??0),0),policy=policyOn(cycle.endDate);if(sourceMinutes)events.push(base({entryDate:cycle.endDate,entryType:'每日超額年度結算',reason:`結算 ${cycle.startDate.replaceAll('-','/')}～${cycle.endDate.replaceAll('-','/')} 每日超額工時`,sourceMinutes,cashHourlyRateCents:policy.cashHourlyRateCents,cashAmountCents:cashAmountCents(sourceMinutes,policy.cashHourlyRateCents),transactionDatetime:stamp(cycle.endDate,'23:59:30'),transactionType:'COMP_ANNUAL_EXCESS_CASH_SETTLEMENT',ledgerOrigin:'SYSTEM'}));events.push(base({entryDate:cycle.endDate,entryType:'補休年度結算',reason:`結算 ${cycle.startDate.replaceAll('-','/')}～${cycle.endDate.replaceAll('-','/')}`,transactionDatetime:stamp(cycle.endDate,'23:59:59'),transactionType:'COMP_LEAVE_SETTLEMENT',ledgerOrigin:'SYSTEM'}))}
  if(input.trackingStartDate<input.today)for(const day of dates(input.trackingStartDate,input.today)){if(day>=input.today)break;if(!records.has(day)&&input.calendar.isWorkday(day))events.push(base({entryDate:day,entryType:'未登錄工作日',reason:'正常上班日無工時紀錄',transactionDatetime:stamp(day,'18:00:00'),transactionType:'MISSING_WORKDAY_DEDUCTION',ledgerOrigin:'SYSTEM'}))}
  const currentPolicy=policyOn(input.today);if(input.currentCompCycleStart&&currentPolicy.mode==='MONTHLY'){let cursor=`${input.currentCompCycleStart.slice(0,7)}-01` as ISODate;while(cursor<input.today){const end=monthEnd(cursor);if(end<input.today&&end>=input.currentCompCycleStart){const p=policyOn(end);events.push(base({entryDate:end,entryType:'補休月結轉入',reason:`${end.slice(0,7).replace('-','/')} 月補休轉入年補休`,transactionDatetime:stamp(end,'23:58:00'),transactionType:'COMP_MONTHLY_TRANSFER',ledgerOrigin:'SYSTEM',cashHourlyRateCents:p.cashHourlyRateCents}))}cursor=nextMonthStart(cursor)}}
  events.sort((a,b)=>a.transactionDatetime.localeCompare(b.transactionDatetime)||(a.id??0)-(b.id??0))
  let comp=0,annual=0,monthly=0,annualComp=0,previousMode:'ANNUAL'|'MONTHLY'='ANNUAL';const rebuilt:LedgerEntry[]=[],settlements:CompMonthlySettlement[]=[]
  for(let event of events){const policy=policyOn(event.entryDate),mode=policy.mode;if(mode!==previousMode){annualComp=comp;monthly=0;previousMode=mode}
    if(event.transactionType==='ANNUAL_LEAVE_SETTLEMENT')event.annualChange=-annual
    else if(event.transactionType==='COMP_LEAVE_SETTLEMENT'){event.compChange=-comp;monthly=annualComp=0}
    else if(event.transactionType==='WORKTIME_DEDUCTION'||event.transactionType==='MISSING_WORKDAY_DEDUCTION'){const record=records.get(event.entryDate),standard=input.calendar.standardMinutesFor(event.entryDate,input.dailyStandardMinutes),shortfall=record?standard-calculateWorkMinutes(record):standard,[cc,ac]=deductLeave(shortfall,comp,annual,input.priority);event={...event,compChange:cc,annualChange:ac}}
    if(event.transactionType==='COMP_MONTHLY_TRANSFER'){
      const pre=monthly,annualBefore=annualComp,cap=Math.max(0,policy.monthlyCapMinutes),transfer=Math.min(Math.max(pre,0),cap),cash=Math.max(pre-cap,0);monthly-=transfer;annualComp+=transfer;event={...event,compChange:0,sourceMinutes:transfer,targetMinutes:cap,note:`結算前月補休 ${pre} 分；轉入 ${transfer} 分；折現 ${cash} 分；policy ${policy.effectiveFrom}`};comp=monthly+annualComp;annual+=event.annualChange;event={...event,compBalance:comp,annualBalance:annual,monthlyCompBalance:monthly,annualCompBalance:annualComp};rebuilt.push(event)
      monthly=0;const cashEvent=base({entryDate:event.entryDate,entryType:'補休超額折現',reason:`${event.entryDate.slice(0,7).replace('-','/')} 超額補休折現`,compChange:-cash,transactionDatetime:stamp(event.entryDate,'23:58:30'),transactionType:'COMP_MONTHLY_CASH_SETTLEMENT',ledgerOrigin:'SYSTEM',sourceMinutes:cash,cashHourlyRateCents:policy.cashHourlyRateCents,cashAmountCents:cashAmountCents(cash,policy.cashHourlyRateCents),compBalance:annualComp,annualBalance:annual,monthlyCompBalance:0,annualCompBalance:annualComp});rebuilt.push(cashEvent);comp=annualComp
      settlements.push({year:Number(event.entryDate.slice(0,4)),month:Number(event.entryDate.slice(5,7)),preMonthlyBalance:pre,annualBalanceBefore:annualBefore,monthlyCapMinutes:cap,transferToAnnualMinutes:transfer,cashMinutes:cash,cashHourlyRateCents:policy.cashHourlyRateCents,cashAmountCents:cashEvent.cashAmountCents,annualBalanceAfter:annualComp,monthlyBalanceAfter:0,policyEffectiveFrom:policy.effectiveFrom,annualSettlementOccurred:(input.compCycles??[]).some(c=>c.endDate===event.entryDate&&c.endDate<input.today)})
      continue
    }
    if(event.transactionType!=='COMP_LEAVE_SETTLEMENT'){const delta=event.compChange;if(mode==='MONTHLY'){if(event.entryType==='年度期初')annualComp+=delta;else if(delta>=0)monthly+=delta;else{const needed=-delta,used=Math.min(Math.max(monthly,0),needed);monthly-=used;annualComp-=needed-used}}else{annualComp+=delta;monthly=0}}
    comp=monthly+annualComp;annual+=event.annualChange;rebuilt.push({...event,compBalance:comp,annualBalance:annual,monthlyCompBalance:monthly,annualCompBalance:annualComp})
  }
  return {entries:rebuilt.sort((a,b)=>a.transactionDatetime.localeCompare(b.transactionDatetime)||(a.id??0)-(b.id??0)),settlements}
}
export function replayLedger(input:ReplayInput):LedgerEntry[]{return replayLedgerWithSettlements(input).entries}
export class LedgerService{constructor(private repository:LedgerRepository){}async rebuild(input:Omit<ReplayInput,'manualEntries'>,emit=true){const manual=await this.repository.getManual(),result=replayLedgerWithSettlements({...input,manualEntries:manual});await this.repository.replaceDerived(result.entries,result.settlements);if(emit)ledgerEvents.dispatchEvent(new Event(LEDGER_CHANGED));return result}currentBalances(){return this.repository.currentBalances()}currentCompBalances(){return this.repository.currentCompBalances()}}
export function todayLocal():ISODate{return localISODate() as ISODate}
