const encoder=new TextEncoder()
const u16=(v:number)=>new Uint8Array([v&255,v>>>8&255]),u32=(v:number)=>new Uint8Array([v&255,v>>>8&255,v>>>16&255,v>>>24&255])
const join=(parts:Uint8Array[])=>{const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out}
const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0})
function crc32(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
export function createZip(files:Record<string,Uint8Array>):Uint8Array{const local:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const [name,data] of Object.entries(files)){const n=encoder.encode(name),crc=crc32(data),head=join([u32(0x04034b50),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(n.length),u16(0),n]);local.push(head,data);central.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),n]));offset+=head.length+data.length}const directory=join(central);return join([...local,directory,u32(0x06054b50),u16(0),u16(0),u16(central.length),u16(central.length),u32(directory.length),u32(offset),u16(0)])}
const view=(b:Uint8Array)=>new DataView(b.buffer,b.byteOffset,b.byteLength)
async function inflate(bytes:Uint8Array){const stream=new Blob([new Uint8Array(bytes).buffer]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer())}
export async function readZip(bytes:Uint8Array):Promise<Map<string,Uint8Array>>{const result=new Map<string,Uint8Array>(),v=view(bytes);let at=0;while(at+30<=bytes.length&&v.getUint32(at,true)===0x04034b50){const flags=v.getUint16(at+6,true),method=v.getUint16(at+8,true),compressed=v.getUint32(at+18,true),size=v.getUint32(at+22,true),nl=v.getUint16(at+26,true),el=v.getUint16(at+28,true);if(flags&8)throw new Error('ZIP_DESCRIPTOR_UNSUPPORTED');const name=new TextDecoder('utf-8',{fatal:true}).decode(bytes.slice(at+30,at+30+nl));if(name.includes('..')||name.startsWith('/')||name.includes('\\'))throw new Error('ZIP_PATH');const body=bytes.slice(at+30+nl+el,at+30+nl+el+compressed);const data=method===0?body:method===8?await inflate(body):(()=>{throw new Error('ZIP_METHOD')})();if(data.length!==size||crc32(data)!==v.getUint32(at+14,true))throw new Error('ZIP_CORRUPT');result.set(name,data);at+=30+nl+el+compressed}if(!result.size)throw new Error('ZIP_INVALID');return result}
