import type { CalendarOverride, CompMonthlySettlement, CompSettlementPolicy, LedgerEntry, LeaveCycle, OfficialHoliday, Setting, WorkRecord } from '../models/domain'
export interface WorkRecordRepository { save(record:WorkRecord):Promise<number>; all():Promise<WorkRecord[]>; getByDate(date:string):Promise<WorkRecord|undefined>; recordsForMonth(year:number,month:number):Promise<WorkRecord[]>; recordsForYear(year:number):Promise<WorkRecord[]>; recent(limit?:number):Promise<WorkRecord[]>; delete(id:number):Promise<void> }
export interface SettingsRepository { get(key:string, fallback?:string):Promise<string|undefined>; set(setting:Setting):Promise<void> }
export interface CompBalanceSummary { monthly:number; annual:number; total:number }
export interface LedgerRepository { all():Promise<LedgerEntry[]>; getSystem():Promise<LedgerEntry[]>; getManual():Promise<LedgerEntry[]>; add(entry:LedgerEntry):Promise<number>; replaceSystem(entries:LedgerEntry[]):Promise<void>; replaceDerived(entries:LedgerEntry[],settlements:CompMonthlySettlement[]):Promise<void>; currentBalances():Promise<{compBalanceMinutes:number;annualBalanceMinutes:number}>; currentCompBalances():Promise<CompBalanceSummary>; entriesForRange(start:string,end:string):Promise<LedgerEntry[]> }
export interface CompPolicyRepository { history():Promise<CompSettlementPolicy[]>; current():Promise<CompSettlementPolicy|undefined>; policyOn(date:string):Promise<CompSettlementPolicy|undefined>; save(policy:CompSettlementPolicy):Promise<number|undefined> }
export interface CompCycleRepository { all():Promise<LeaveCycle[]>; upsert(cycle:LeaveCycle):Promise<number|undefined> }
export interface CompMonthlySettlementRepository { all():Promise<CompMonthlySettlement[]>; forYear(year:number):Promise<CompMonthlySettlement[]>; forMonth(year:number,month:number):Promise<CompMonthlySettlement|undefined>; replaceDerived(values:CompMonthlySettlement[]):Promise<void> }
export interface SpecialDateRepository { get(date:string):Promise<CalendarOverride|undefined>; all():Promise<CalendarOverride[]>; save(value:CalendarOverride):Promise<number>; deleteByDate(date:string):Promise<void> }
export interface HolidayRepository { get(date:string):Promise<OfficialHoliday|undefined>; forYear(year:number):Promise<OfficialHoliday[]>; replaceYear(year:number, values:OfficialHoliday[]):Promise<void> }
/** A future sync adapter consumes these contracts; React never depends on Dexie directly. */
export interface RepositoryBundle { records:WorkRecordRepository; settings:SettingsRepository; ledger:LedgerRepository; specialDates:SpecialDateRepository; holidays:HolidayRepository }
