import 'fake-indexeddb/auto'
import {afterEach,describe,expect,it} from 'vitest'
import {WorkTimeDatabase} from '../db/database'
import {BackupDataSource,BackupService,RestoreService,backupFilename} from '../services/backupService'
import {BackupValidationError} from '../services/backupValidator'
import {createZip,readZip} from '../services/zipArchive'

const encoder=new TextEncoder()
const databases:WorkTimeDatabase[]=[]
const database=()=>{const d=new WorkTimeDatabase(`backup-${crypto.randomUUID()}`);databases.push(d);return d}
afterEach(async()=>{for(const d of databases.splice(0)){d.close();await d.delete()}})
async function rewrite(bytes:Uint8Array,change:(files:Map<string,Uint8Array>)=>void){const files=await readZip(bytes);change(files);return createZip(Object.fromEntries(files))}

describe('Phase 8 portable backup',()=>{
 it('exports Android-compatible v2 ZIP, exact checksum, UTF-8 and only manual ledger',async()=>{const d=database();await d.workRecords.add({workDate:'2026-09-01',clockIn:'08:00',clockOut:'17:00',deductBreak:true,standardMinutes:480,note:'客戶會議',workdayType:'正常工作日',overnight:false});await d.ledger.bulkAdd([{entryDate:'2026-09-01',entryType:'系統',reason:'x',compChange:1,annualChange:0,compBalance:1,annualBalance:0,transactionDatetime:'2026-09-01T18:00:00',transactionType:'WORKTIME_EARN',ledgerOrigin:'SYSTEM',note:'',createdAt:'2026-09-01T18:00:00Z',monthlyCompBalance:0,annualCompBalance:1,cashAmountCents:0,cashHourlyRateCents:0},{id:100,entryDate:'2026-09-01',entryType:'轉換',reason:'x',compChange:-1,annualChange:1,compBalance:0,annualBalance:1,transactionDatetime:'2026-09-01T19:00:00',transactionType:'LEAVE_CONVERSION',ledgerOrigin:'MANUAL',sourceLeaveType:'COMP_TIME',targetLeaveType:'ANNUAL_LEAVE',sourceMinutes:1,targetMinutes:1,note:'補休轉特休',createdAt:'2026-09-01T19:00:00Z',monthlyCompBalance:0,annualCompBalance:0,cashAmountCents:0,cashHourlyRateCents:0}]);const service=new BackupService(new BackupDataSource(d)),artifact=await service.create({now:new Date('2026-09-07T06:00:00Z')}),found=await service.inspect(artifact.bytes);expect([...(await readZip(artifact.bytes)).keys()]).toEqual(['manifest.json','data.json']);expect(found.manifest).toMatchObject({format_name:'WorkTimeTrackerBackup',backup_format_version:2,record_count:1});expect(found.data.tables.work_records[0].note).toBe('客戶會議');expect(found.data.manual_ledger_events.map(x=>x.id)).toEqual([100]);expect(artifact.filename).toMatch(/^工時管家備份_\d{8}_\d{6}\.worktimebackup$/)})
 it.each([['bad zip',encoder.encode('bad')],['missing manifest',createZip({'data.json':encoder.encode('{}')})],['missing data',createZip({'manifest.json':encoder.encode('{}')})]])('rejects %s',async(_name,bytes)=>{await expect(new BackupService().inspect(bytes)).rejects.toBeInstanceOf(BackupValidationError)})
 it('rejects checksum tampering',async()=>{const d=database(),service=new BackupService(new BackupDataSource(d)),a=await service.create(),bad=await rewrite(a.bytes,f=>f.set('data.json',encoder.encode('{}')));await expect(service.inspect(bad)).rejects.toThrow('checksum')})
 it('rejects record count mismatch',async()=>{const d=database(),service=new BackupService(new BackupDataSource(d)),a=await service.create(),bad=await rewrite(a.bytes,f=>{const m=JSON.parse(new TextDecoder().decode(f.get('manifest.json')));m.record_count=2;f.set('manifest.json',encoder.encode(JSON.stringify(m)))});await expect(service.inspect(bad)).rejects.toThrow('紀錄數量')})
 it.each([['format_name','Wrong'],['backup_format_version',999]])('rejects invalid manifest %s',async(key,value)=>{const d=database(),service=new BackupService(new BackupDataSource(d)),a=await service.create(),bad=await rewrite(a.bytes,f=>{const m=JSON.parse(new TextDecoder().decode(f.get('manifest.json')));m[key]=value;f.set('manifest.json',encoder.encode(JSON.stringify(m)))});await expect(service.inspect(bad)).rejects.toBeInstanceOf(BackupValidationError)})
 it('preserves category outside strict Android calendar row',async()=>{const d=database();await d.calendarOverrides.add({workDate:'2026-09-26',dayType:'WORKDAY',category:'COMPANY_MAKEUP_WORKDAY',note:'公司補班',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'});const inspected=await new BackupService(new BackupDataSource(d)).inspect((await new BackupService(new BackupDataSource(d)).create()).bytes);expect(inspected.data.tables.calendar_overrides[0]).not.toHaveProperty('category');expect(inspected.data.pwa_extensions?.calendar_override_categories?.['2026-09-26']).toBe('COMPANY_MAKEUP_WORKDAY')})
 it('restores atomically and keeps work/manual IDs',async()=>{const source=database();await source.workRecords.add({id:40,workDate:'2026-09-01',clockIn:'08:00',clockOut:'17:00',deductBreak:false,standardMinutes:480,note:'客戶會議',workdayType:'正常工作日',overnight:false});await source.settings.bulkPut([{key:'work_tracking_start_date',value:'2026-09-01'},{key:'daily_standard_minutes',value:'480'}]);const service=new BackupService(new BackupDataSource(source)),inspected=await service.inspect((await service.create()).bytes),target=database();await target.workRecords.add({workDate:'2020-01-01',clockIn:'08:00',clockOut:'09:00',deductBreak:false,standardMinutes:480,note:'old',workdayType:'正常工作日',overnight:false});await new RestoreService(target,new BackupService(new BackupDataSource(target))).restore(inspected,{today:'2026-09-01'});expect(await target.workRecords.toArray()).toMatchObject([{id:40,note:'客戶會議'}]);expect((await target.ledger.toArray()).some(x=>x.ledgerOrigin==='SYSTEM'&&x.sourceRecordId===40)).toBe(true)})
 it('rolls every store back after an injected failure',async()=>{const source=database(),target=database();await target.workRecords.add({workDate:'2020-01-01',clockIn:'08:00',clockOut:'09:00',deductBreak:false,standardMinutes:480,note:'keep',workdayType:'正常工作日',overnight:false});await target.settings.put({key:'marker',value:'keep'});const service=new BackupService(new BackupDataSource(source)),inspected=await service.inspect((await service.create()).bytes);await expect(new RestoreService(target).restore(inspected,{faultInjector:()=>{throw new Error('boom')}})).rejects.toThrow('boom');expect((await target.workRecords.toArray())[0].note).toBe('keep');expect((await target.settings.get('marker'))?.value).toBe('keep')})
 it('creates a self-inspectable pre-restore safety backup',async()=>{const d=database();await d.workRecords.add({workDate:'2026-01-01',clockIn:'08:00',clockOut:'17:00',deductBreak:false,standardMinutes:480,note:'安全',workdayType:'正常工作日',overnight:false});const service=new RestoreService(d,new BackupService(new BackupDataSource(d))),artifact=await service.createSafetyBackup(),inspected=await new BackupService().inspect(artifact.bytes);expect(inspected.manifest.record_count).toBe(1);expect(artifact.filename).toContain('還原前備份')})
 it('uses the Android filename convention',()=>expect(backupFilename(new Date(2026,8,7,6,5,4))).toBe('工時管家備份_20260907_060504.worktimebackup'))
})
