import 'fake-indexeddb/auto'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {WorkTimeDatabase} from '../db/database'
import type {CalendarOverride,CompMonthlySettlement,ISODate,LedgerEntry,OfficialHoliday,WorkRecord} from '../models/domain'
import {buildExcelReport,exportFilename,type ExcelExportScope,type ExcelSnapshot} from '../services/excelReportBuilder'
import {downloadExcel,ExcelExportService,XLSX_MIME} from '../services/excelExportService'
import {readZip} from '../services/zipArchive'
import {columnName,writeXlsx} from '../services/xlsxWriter'

const record=(workDate:ISODate,over:Partial<WorkRecord>={}):WorkRecord=>({workDate,clockIn:'08:00',clockOut:'17:00',breakStart:'12:00',breakEnd:'13:00',deductBreak:true,standardMinutes:480,note:'',workdayType:'正常工作日',overnight:false,...over})
const ledger=(transactionType:LedgerEntry['transactionType']='WORKTIME_EARN',over:Partial<LedgerEntry>={}):LedgerEntry=>({entryDate:'2026-09-01',entryType:'系統',reason:'原因',compChange:0,annualChange:0,compBalance:120,annualBalance:240,transactionDatetime:'2026-09-01T18:00:00',transactionType,ledgerOrigin:'SYSTEM',note:'',createdAt:'2026-09-01T18:00:00Z',monthlyCompBalance:0,annualCompBalance:120,cashAmountCents:0,cashHourlyRateCents:0,...over})
const holiday=(holidayDate:ISODate):OfficialHoliday=>({holidayDate,name:'中秋節',year:Number(holidayDate.slice(0,4)),source:'fixture',syncedAt:'2026-01-01'})
const settings={daily_standard_minutes:'480',lunch_break_start:'12:00',lunch_break_end:'13:00',leave_deduction_priority:'COMP_TIME_FIRST',annual_leave_total_minutes:'4800',annual_leave_settlement_date:'2027-06-30',comp_leave_settlement_date:'2026-12-31',comp_settlement_mode:'MONTHLY',comp_monthly_cap_minutes:'2400',comp_cash_hourly_rate_cents:'25000',work_tracking_start_date:'2026-09-01'}
const snapshot=(over:Partial<ExcelSnapshot>={}):ExcelSnapshot=>({records:[record('2026-09-01')],ledger:[ledger()],settings:{...settings},overrides:[],holidays:[holiday('2026-09-07')],settlements:[],...over})
const report=(scope:ExcelExportScope='all',over:Partial<ExcelSnapshot>={})=>buildExcelReport(snapshot(over),scope,'2026-09-10')

describe('Phase 9 report data',()=>{
  it('builds exact local-date and cross-year filenames',()=>{expect(exportFilename('all','2026-09-03')).toBe('工時管家_全部紀錄_20260903.xlsx');expect(exportFilename('leave_year','2026-09-03','2026-07-01','2027-06-30')).toBe('工時管家_年度_20260701-20270630.xlsx')})
  it('uses inclusive leave-cycle boundaries and emits 12 cross-year months',()=>{const records=[record('2026-06-30',{note:'before'}),record('2026-07-01',{note:'start'}),record('2027-06-30',{note:'end'}),record('2027-07-01',{note:'after'})],value=report('leave_year',{records,settings:{...settings,work_tracking_start_date:'2027-07-01'}});expect(value.daily.map(x=>x.note)).toEqual(['start','end']);expect(value.summary.filter(x=>/^\d{4}\//.test(x.item)).map(x=>x.item)).toEqual(['2026/07','2026/08','2026/09','2026/10','2026/11','2026/12','2027/01','2027/02','2027/03','2027/04','2027/05','2027/06']);expect(value.summary[0].value).toBe('2026/07/01 ～ 2027/06/30')})
  it('rejects missing settlement configuration and a truly empty report',()=>{expect(()=>report('leave_year',{settings:{...settings,annual_leave_settlement_date:''}})).toThrow('請先至設定頁');expect(()=>report('all',{records:[],holidays:[],settings:{...settings,work_tracking_start_date:'2026-09-10'}})).toThrow('沒有可匯出')})
  it('sorts daily rows, preserves Unicode and uses canonical lunch overlap',()=>{const value=report('all',{records:[record('2026-09-03',{note:'特殊 & <標記> 😀'}),record('2026-09-01'),record('2026-09-02',{clockIn:'12:15',clockOut:'17:00',breakStart:'12:00',breakEnd:'12:30'})],settings:{...settings,work_tracking_start_date:'2026-09-10'}});expect(value.daily.map(x=>x.date)).toEqual(['2026/09/01','2026/09/02','2026/09/03']);expect(value.daily[1]).toMatchObject({lunch:'0 小時 15 分',actual:'4 小時 30 分',shortfall:'3 小時 30 分'});expect(value.daily[2].note).toContain('😀')})
  it.each([
    ['full overlap',record('2026-09-01'),60,480],
    ['no overlap',record('2026-09-01',{clockIn:'08:00',clockOut:'12:00'}),0,240],
    ['disabled',record('2026-09-01',{deductBreak:false}),0,540],
    ['overnight',record('2026-09-01',{clockIn:'22:00',clockOut:'06:00',overnight:true}),0,480],
  ])('reports %s lunch without a second algorithm',(_name,row,lunch,actual)=>{const value=report('all',{records:[row],settings:{...settings,work_tracking_start_date:'2026-09-10'}}).daily[0];expect(value.lunch).toBe(`${Math.floor(lunch/60)} 小時 ${lunch%60} 分`);expect(value.actual).toBe(`${Math.floor(actual/60)} 小時 ${actual%60} 分`)})
  it('adds reliable missing days but excludes tracking-before, today, future and holiday',()=>{const value=report('all',{records:[],holidays:[holiday('2026-09-07')],settings:{...settings,work_tracking_start_date:'2026-09-07'}});expect(value.daily.map(x=>[x.date,x.status,x.shortfall])).toEqual([['2026/09/08','無紀錄','8 小時 0 分'],['2026/09/09','無紀錄','8 小時 0 分']])})
  it('labels official holiday work, company holiday and company makeup workday',()=>{const overrides:CalendarOverride[]=[{workDate:'2026-09-08',dayType:'NON_WORKDAY',category:'COMPANY_HOLIDAY',note:'公司假日',createdAt:'x',updatedAt:'x'},{workDate:'2026-09-12',dayType:'WORKDAY',category:'COMPANY_MAKEUP_WORKDAY',note:'補班',createdAt:'x',updatedAt:'x'}],value=report('all',{records:[record('2026-09-07',{deductBreak:false,note:'假日工作'}),record('2026-09-08'),record('2026-09-12')],overrides,settings:{...settings,work_tracking_start_date:'2026-09-10'}});expect(value.daily.map(x=>x.dayType)).toEqual(['國定假日','公司假日','公司補班']);expect(value.daily[0]).toMatchObject({standard:'0 小時 0 分',overtime:'9 小時 0 分',note:'假日工作'})})
  it('uses authoritative balances and filters leave audit without dropping reversal',()=>{const entries=[ledger('WORKTIME_EARN'),ledger('LEAVE_CONVERSION',{entryDate:'2026-09-02',sourceLeaveType:'COMP_TIME',targetLeaveType:'ANNUAL_LEAVE',sourceMinutes:60,note:'轉換 😀'}),ledger('REVERSAL',{entryDate:'2026-09-03',sourceLeaveType:'ANNUAL_LEAVE',targetLeaveType:'COMP_TIME',sourceMinutes:60,note:'撤銷'}),ledger('ANNUAL_LEAVE_GRANT'),ledger('ANNUAL_LEAVE_SETTLEMENT'),ledger('COMP_LEAVE_SETTLEMENT',{compBalance:321,annualBalance:654})],value=report('all',{ledger:entries,settings:{...settings,work_tracking_start_date:'2026-09-10'}});expect(value.leave.map(x=>x.type)).toEqual(['80 小時 0 分','10 小時 54 分','5 小時 21 分','2027-06-30','2026-12-31','MONTHLY','LEAVE_CONVERSION','REVERSAL','ANNUAL_LEAVE_GRANT','ANNUAL_LEAVE_SETTLEMENT','COMP_LEAVE_SETTLEMENT']);expect(value.leave.some(x=>x.type==='WORKTIME_EARN')).toBe(false);expect(value.summary.slice(-2).map(x=>x.value)).toEqual(['5 小時 21 分','10 小時 54 分']);expect(value.leave.find(x=>x.type==='LEAVE_CONVERSION')?.note).toBe('轉換 😀')})
  it('renders all settings and distinct annual/comp cycles',()=>{const value=report();expect(value.config.map(x=>x.item)).toEqual(['每日標準工時','午休開始','午休結束','工時不足扣除順序','本年度特休核給時數','特休結算日','補休結算日','補休結算方式','每月補休累計上限','補休折現時薪','目前特休年度','目前補休年度']);expect(value.config.find(x=>x.item==='補休折現時薪')?.value).toBe('NT$250.00');expect(value.config.slice(-2).map(x=>x.value)).toEqual(['2026/07/01 ～ 2027/06/30','2026/01/01 ～ 2026/12/31'])})
  it('renders authoritative settlement fields, cents, annual flags and deterministic month order',()=>{const rows:CompMonthlySettlement[]=[{year:2026,month:9,preMonthlyBalance:2880,annualBalanceBefore:120,monthlyCapMinutes:2400,transferToAnnualMinutes:2400,cashMinutes:480,cashHourlyRateCents:25000,cashAmountCents:200000,annualBalanceAfter:0,monthlyBalanceAfter:0,policyEffectiveFrom:'2026-01-01',annualSettlementOccurred:true},{year:2026,month:8,preMonthlyBalance:60,annualBalanceBefore:0,monthlyCapMinutes:2400,transferToAnnualMinutes:60,cashMinutes:0,cashHourlyRateCents:25000,cashAmountCents:0,annualBalanceAfter:60,monthlyBalanceAfter:0,policyEffectiveFrom:'2026-01-01',annualSettlementOccurred:false}],value=report('all',{settlements:rows});expect(value.settlements.map(x=>x.month)).toEqual(['2026-08','2026-09']);expect(value.settlements[1]).toMatchObject({transfer:'40 小時 0 分',cashMinutes:'8 小時 0 分',rate:'NT$250.00',amount:'NT$2,000.00',monthlyAfter:'0 小時 0 分',annualAfter:'0 小時 0 分',annualOccurred:'是'})})
})

describe('minimal browser OOXML writer',()=>{
  it('supports generic cell references',()=>expect([0,25,26,27,701].map(columnName)).toEqual(['A','Z','AA','AB','ZZ']))
  it('creates a valid five-sheet ZIP with relationships, styles and escaped Unicode',async()=>{const value=report(),files=await readZip(writeXlsx(value.sheets)),decode=(name:string)=>new TextDecoder().decode(files.get(name));expect([...files.keys()].filter(x=>x.startsWith('xl/worksheets/'))).toHaveLength(5);expect(decode('xl/workbook.xml')).toContain('每日紀錄');expect(decode('xl/workbook.xml')).toContain('補休結算');expect(decode('xl/_rels/workbook.xml.rels').match(/relationships\/worksheet/g)).toHaveLength(5);expect(files.has('xl/styles.xml')).toBe(true);expect(decode('xl/styles.xml')).toContain('FFD9EAF7');for(let index=1;index<=5;index++){expect(decode(`xl/worksheets/sheet${index}.xml`)).toContain('state="frozen"');expect(decode(`xl/worksheets/sheet${index}.xml`)).toContain('<autoFilter')}})
})

describe('Excel service and browser download',()=>{let database:WorkTimeDatabase|undefined;afterEach(async()=>{vi.restoreAllMocks();if(database){database.close();await database.delete();database=undefined}})
  it('takes a read-only snapshot and leaves every table unchanged',async()=>{database=new WorkTimeDatabase(`xlsx-${crypto.randomUUID()}`);await database.workRecords.add(record('2026-09-01'));await database.settings.bulkPut(Object.entries(settings).map(([key,value])=>({key,value})));await database.ledger.add(ledger());const before=await Promise.all([database.workRecords.toArray(),database.settings.toArray(),database.ledger.toArray(),database.compMonthlySettlements.toArray()]),artifact=await new ExcelExportService(database).create('all','2026-09-10'),after=await Promise.all([database.workRecords.toArray(),database.settings.toArray(),database.ledger.toArray(),database.compMonthlySettlements.toArray()]);expect(artifact).toMatchObject({filename:'工時管家_全部紀錄_20260910.xlsx',mime:XLSX_MIME});expect(artifact.blob.type).toBe(XLSX_MIME);expect(after).toEqual(before)})
  it('downloads through an object URL and delays cleanup',()=>{vi.useFakeTimers();const click=vi.fn(),anchor={click,href:'',download:''},create=vi.fn(()=>anchor);vi.stubGlobal('document',{createElement:create});const url=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:x'),revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});downloadExcel({filename:'report.xlsx',mime:XLSX_MIME,bytes:new Uint8Array(),blob:new Blob()});expect(create).toHaveBeenCalledWith('a');expect(anchor.download).toBe('report.xlsx');expect(click).toHaveBeenCalledOnce();expect(revoke).not.toHaveBeenCalled();vi.advanceTimersByTime(60_000);expect(revoke).toHaveBeenCalledWith('blob:x');url.mockRestore();vi.unstubAllGlobals();vi.useRealTimers()})
})
