import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {interactiveSave,legacyDownload,type SaveableFile} from '../services/fileSaveService'

const excel=():SaveableFile=>({filename:'工時.xlsx',blob:new Blob(['xlsx'],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',description:'Excel 活頁簿',extension:'.xlsx'})
const backup=():SaveableFile=>({filename:'工時.worktimebackup',blob:new Blob(['zip'],{type:'application/zip'}),mime:'application/zip',description:'工時管家備份',extension:'.worktimebackup'})
beforeEach(()=>{vi.stubGlobal('window',{});if(typeof File==='undefined')vi.stubGlobal('File',class extends Blob{name:string;constructor(parts:BlobPart[],name:string,options?:FilePropertyBag){super(parts,options);this.name=name}})})
afterEach(()=>{delete (window as typeof window&{showSaveFilePicker?:unknown}).showSaveFilePicker;vi.unstubAllGlobals();vi.restoreAllMocks()})

describe('interactive file saving',()=>{
 it('uses the picker with the suggested Excel name/type and writes then closes',async()=>{const write=vi.fn(),close=vi.fn(),picker=vi.fn().mockResolvedValue({createWritable:vi.fn().mockResolvedValue({write,close})});Object.assign(window,{showSaveFilePicker:picker});expect(await interactiveSave(excel())).toEqual({status:'saved',method:'picker'});expect(picker).toHaveBeenCalledWith({suggestedName:'工時.xlsx',types:[{description:'Excel 活頁簿',accept:{'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx']}}]});expect(write).toHaveBeenCalledWith(expect.any(Blob));expect(close).toHaveBeenCalledOnce()})
 it('uses the backup extension in picker types',async()=>{const picker=vi.fn().mockResolvedValue({createWritable:async()=>({write:vi.fn(),close:vi.fn()})});Object.assign(window,{showSaveFilePicker:picker});await interactiveSave(backup());expect(picker.mock.calls[0][0].types[0]).toEqual({description:'工時管家備份',accept:{'application/zip':['.worktimebackup']}})})
 it.each([['picker',new DOMException('cancel','AbortError')],['share',Object.assign(new Error('cancel'),{name:'AbortError'})]])('treats %s cancellation as cancellation without downloading',async(kind,error)=>{const click=vi.fn();vi.stubGlobal('document',{createElement:vi.fn(()=>({click}))});if(kind==='picker')Object.assign(window,{showSaveFilePicker:vi.fn().mockRejectedValue(error)});else{vi.stubGlobal('navigator',{canShare:()=>true,share:vi.fn().mockRejectedValue(error)});delete (window as typeof window&{showSaveFilePicker?:unknown}).showSaveFilePicker}expect(await interactiveSave(excel())).toEqual({status:'cancelled'});expect(click).not.toHaveBeenCalled()})
 it('returns a friendly picker error and does not fall back',async()=>{const share=vi.fn();vi.stubGlobal('navigator',{canShare:()=>true,share});Object.assign(window,{showSaveFilePicker:vi.fn().mockRejectedValue(new Error('disk'))});expect(await interactiveSave(excel())).toEqual({status:'error',message:'無法儲存檔案，請稍後再試。'});expect(share).not.toHaveBeenCalled()})
 it('shares a File with the exact filename and MIME when no picker exists',async()=>{const share=vi.fn<(data:ShareData)=>Promise<void>>().mockResolvedValue(undefined),canShare=vi.fn<(data:ShareData)=>boolean>(()=>true);vi.stubGlobal('navigator',{canShare,share});expect(await interactiveSave(excel())).toEqual({status:'saved',method:'share'});const file=canShare.mock.calls[0]![0].files![0]!;expect(file).toBeInstanceOf(File);expect(file.name).toBe('工時.xlsx');expect(file.type).toBe(excel().mime);expect(share).toHaveBeenCalledWith({files:[file],title:'工時.xlsx'})})
 it('requires explicit fallback when neither picker nor file share is supported',async()=>{vi.stubGlobal('navigator',{canShare:()=>false,share:vi.fn()});const click=vi.fn();vi.stubGlobal('document',{createElement:vi.fn(()=>({click}))});expect(await interactiveSave(backup())).toEqual({status:'fallback-required'});expect(click).not.toHaveBeenCalled()})
 it('clicks an anchor only when legacyDownload is explicitly called',()=>{vi.useFakeTimers();const click=vi.fn(),anchor={click,href:'',download:''};vi.stubGlobal('document',{createElement:vi.fn(()=>anchor)});vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:x');const revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});legacyDownload(excel());expect(anchor.download).toBe('工時.xlsx');expect(click).toHaveBeenCalledOnce();vi.advanceTimersByTime(60_000);expect(revoke).toHaveBeenCalledWith('blob:x');vi.useRealTimers()})
})
