import {describe,expect,it} from 'vitest'
import type {CalendarOverride,LedgerEntry,OfficialHoliday,WorkRecord} from '../models/domain'
import {CalendarService} from '../services/calendarService'
import {deductLeave,replayLedger} from '../services/ledgerService'
const record=(date:string,end='17:00',id=1):WorkRecord=>({id,workDate:date as WorkRecord['workDate'],clockIn:'08:00',clockOut:end,breakStart:'12:00',breakEnd:'13:00',deductBreak:true,standardMinutes:480,note:'',workdayType:'正常工作日',overnight:false})
const calendar=(overrides:CalendarOverride[]=[],holidays:OfficialHoliday[]=[])=>new CalendarService(overrides,holidays)
const input=(records:WorkRecord[]=[],extra={})=>({records,calendar:calendar(),dailyStandardMinutes:480,trackingStartDate:'2026-09-01' as const,today:'2026-09-02' as const,priority:'COMP_TIME_FIRST' as const,annualCycles:[],activationDate:'2026-09-02' as const,...extra})
describe('Python-compatible deduction priority',()=>{
 it('earns positive differences and keeps zero differences harmless',()=>{expect(replayLedger(input([record('2026-09-01','18:00')]))[0].compChange).toBe(60);expect(replayLedger(input([record('2026-09-01')]))[0].compChange).toBe(0)})
 it.each([[[120,300,0,'COMP_TIME_FIRST'],[-120,0]],[[400,120,500,'COMP_TIME_FIRST'],[-120,-280]],[[900,120,300,'COMP_TIME_FIRST'],[-120,-780]],[[120,0,300,'ANNUAL_LEAVE_FIRST'],[0,-120]],[[400,300,120,'ANNUAL_LEAVE_FIRST'],[-280,-120]],[[900,300,120,'ANNUAL_LEAVE_FIRST'],[-780,-120]]] as const)('deducts %j',([shortfall,comp,annual,priority],expected)=>expect(deductLeave(shortfall,comp,annual,priority)).toEqual(expected))
 it('priority changes which final leave type becomes negative',()=>{expect(deductLeave(60,0,0,'COMP_TIME_FIRST')).toEqual([0,-60]);expect(deductLeave(60,0,0,'ANNUAL_LEAVE_FIRST')).toEqual([-60,0])})
})
describe('deterministic replay',()=>{
 it('is identical across repeated rebuilds and never double earns',()=>{const args=input([record('2026-09-01','18:00')]),one=replayLedger(args),two=replayLedger(args);expect(two).toEqual(one);expect(two.at(-1)?.compBalance).toBe(60)})
 it('replays a historical edit through future snapshots',()=>{const before=replayLedger(input([record('2026-09-01','18:00',1),record('2026-09-02','17:00',2)],{today:'2026-09-03'})),after=replayLedger(input([record('2026-09-01','16:00',1),record('2026-09-02','17:00',2)],{today:'2026-09-03'}));expect(before.at(-1)?.compBalance).toBe(60);expect(after.at(-1)?.annualBalance).toBe(-60)})
 it('removes deleted source events and links retained records',()=>{const entries=replayLedger(input([record('2026-09-01','18:00',42)]));expect(entries[0].sourceRecordId).toBe(42);expect(replayLedger(input([]))).toHaveLength(1)})
 it('preserves manual payload while recalculating its post-event snapshot',()=>{const manual:LedgerEntry={entryDate:'2026-09-01',entryType:'手動調整',reason:'test',compChange:30,annualChange:10,compBalance:999,annualBalance:999,transactionDatetime:'2026-09-01T12:00:00',transactionType:'ADJUSTMENT',ledgerOrigin:'MANUAL',note:'audit',createdAt:'x',monthlyCompBalance:0,annualCompBalance:0,cashAmountCents:0,cashHourlyRateCents:0};const [entry]=replayLedger({...input([],{trackingStartDate:'2026-09-02'}),manualEntries:[manual]});expect(entry).toMatchObject({reason:'test',note:'audit',compBalance:30,annualBalance:10})})
 it('stores each post-transaction balance and deterministic same-day ordering',()=>{const entries=replayLedger(input([record('2026-09-01','18:00')],{annualCycles:[{startDate:'2026-09-01',endDate:'2027-08-31',totalMinutes:480}],activationDate:'2026-09-01'}));expect(entries.map(e=>e.transactionType)).toEqual(['ANNUAL_LEAVE_GRANT','WORKTIME_EARN']);expect(entries.map(e=>[e.compBalance,e.annualBalance])).toEqual([[0,480],[60,480]])})
})
describe('missing workdays and calendar priority',()=>{
 it('deducts a past missing workday but not today or future',()=>{expect(replayLedger(input([])).map(e=>e.transactionType)).toEqual(['MISSING_WORKDAY_DEDUCTION']);expect(replayLedger(input([],{trackingStartDate:'2026-09-02'}))).toEqual([])})
 it('does not deduct an official or company holiday',()=>{const holiday={holidayDate:'2026-09-01',name:'假日',year:2026,source:'x',syncedAt:'x'} as OfficialHoliday,override={workDate:'2026-09-01',dayType:'NON_WORKDAY',category:'COMPANY_HOLIDAY',note:'',createdAt:'x',updatedAt:'x'} as CalendarOverride;expect(replayLedger(input([],{calendar:calendar([], [holiday])}))).toEqual([]);expect(replayLedger(input([],{calendar:calendar([override])}))).toEqual([])})
 it('deducts a missing company makeup workday',()=>{const override={workDate:'2026-09-05',dayType:'WORKDAY',category:'COMPANY_MAKEUP_WORKDAY',note:'',createdAt:'x',updatedAt:'x'} as CalendarOverride;expect(replayLedger(input([],{calendar:calendar([override]),trackingStartDate:'2026-09-05',today:'2026-09-06'}))[0].transactionType).toBe('MISSING_WORKDAY_DEDUCTION')})
 it('excludes dates before calculation start and earns holiday work',()=>{expect(replayLedger(input([],{trackingStartDate:'2026-09-02'}))).toEqual([]);const entry=replayLedger(input([record('2026-09-05','12:00')],{calendar:calendar(),today:'2026-09-06',trackingStartDate:'2026-09-05'}))[0];expect(entry).toMatchObject({entryType:'假日工作',compChange:240})})
})
describe('annual grant, settlement and activation safety',()=>{
 it('grants a cycle exactly once logically',()=>{const entries=replayLedger(input([],{trackingStartDate:'2026-09-02',annualCycles:[{startDate:'2026-01-01',endDate:'2026-12-31',totalMinutes:480}],activationDate:'2026-01-01'}));expect(entries.filter(e=>e.transactionType==='ANNUAL_LEAVE_GRANT')).toHaveLength(1);expect(entries.at(-1)?.annualBalance).toBe(480)})
 it('does not backfill grants before activation',()=>expect(replayLedger(input([],{trackingStartDate:'2026-09-02',annualCycles:[{startDate:'2026-01-01',endDate:'2026-12-31',totalMinutes:480}],activationDate:'2026-09-02'}))).toEqual([]))
 it('settles a completed cycle to zero and does not settle an active cycle',()=>{const completed=replayLedger(input([],{trackingStartDate:'2026-09-02',today:'2026-07-02',activationDate:'2025-01-01',annualCycles:[{startDate:'2025-07-01',endDate:'2026-06-30',totalMinutes:480},{startDate:'2026-07-01',endDate:'2027-06-30',totalMinutes:600}]}));expect(completed.find(e=>e.transactionType==='ANNUAL_LEAVE_SETTLEMENT')).toMatchObject({annualChange:-480,annualBalance:0});expect(completed.at(-1)?.annualBalance).toBe(600);expect(completed.filter(e=>e.transactionType==='ANNUAL_LEAVE_SETTLEMENT')).toHaveLength(1)})
 it('entitlement changes deterministically alter the grant',()=>{const cycle={startDate:'2026-01-01' as const,endDate:'2026-12-31' as const,totalMinutes:480};const first=replayLedger(input([],{trackingStartDate:'2026-09-02',activationDate:'2026-01-01',annualCycles:[cycle]}));const second=replayLedger(input([],{trackingStartDate:'2026-09-02',activationDate:'2026-01-01',annualCycles:[{...cycle,totalMinutes:960}]}));expect([first.at(-1)?.annualBalance,second.at(-1)?.annualBalance]).toEqual([480,960])})
})
